#!/bin/bash
set -euo pipefail

# Auto-discover plugin requirements.txt files and regenerate
# requirements-plugins.txt, then install everything.
#
# Each plugin (importer, exporter, media type, etc.) declares its own
# dependencies in a local requirements.txt.  This script finds them all,
# writes a requirements-plugins.txt with -r references, and pip-installs it.
#
# A new developer just drops a requirements.txt in their plugin directory —
# the next run of this script (or `pip install -r requirements.txt`) picks
# it up automatically.
#
# Usage:
#   bash install-plugin-deps.sh                  # discover + install
#   bash install-plugin-deps.sh --dry-run        # just regenerate the file

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_FILE="$SCRIPT_DIR/requirements-plugins.txt"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Collect all plugin requirements.txt files.
REQ_FILES=()
while IFS= read -r -d '' f; do
    REQ_FILES+=("$f")
done < <(find "$SCRIPT_DIR/vtsearch" -name "requirements.txt" -print0 | sort -z)

# Write requirements-plugins.txt with -r references.
{
    echo "# Auto-generated by install-plugin-deps.sh — do not edit manually."
    echo "# Regenerate with:  bash install-plugin-deps.sh"
    echo "#"
    echo "# Each line references a plugin's own requirements.txt so that"
    echo "# 'pip install -r requirements.txt' cascades through the entire tree."
    echo ""
    for f in "${REQ_FILES[@]}"; do
        # Use path relative to the repo root.
        echo "-r ${f#"$SCRIPT_DIR/"}"
    done
} > "$PLUGINS_FILE"

echo "Found ${#REQ_FILES[@]} plugin requirements.txt files."
echo "Wrote $PLUGINS_FILE"

if $DRY_RUN; then
    echo "(dry run — no packages installed)"
    exit 0
fi

echo "Installing plugin dependencies..."
pip install -r "$PLUGINS_FILE" -q
echo "Plugin dependencies installed."
