"""Persistent settings for VTSearch.

Settings are split across two tiers:

* **Server tier** - shared, single-file settings used to bring the
  process up: dataset/detector directories, concurrency limits, the
  autoload-embedder / autorun-detector lists. Stored in
  ``data/settings.json`` (path = :data:`SETTINGS_PATH`). Loaded once at
  startup, before any user has logged in.
* **Per-user tier** - every other key (preferences, autopilot config,
  per-side view modes, the ``settings_source`` sync target). Stored in
  ``<get_user_data_dir(user)>/user_settings.json``. Resolved per-request
  via :func:`~vtsearch.auth.get_current_user`.

The module exposes the same ``get_<key>`` / ``set_<key>`` accessors as
before; routing between tiers is internal. Auto-save on mutation and
auto-sync to the configured ``settings_source`` are unchanged in shape;
the sync source is per-user and triggers only on per-user writes.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import threading
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from collections.abc import Iterable
from typing import TYPE_CHECKING, Any

from pydantic import ValidationError

try:
    import fcntl as _fcntl  # POSIX-only; falls back to in-process locking on Windows.
except ImportError:  # pragma: no cover - Windows
    _fcntl = None

from vtscore.config import DATA_DIR
from vtsearch.settings_models import (
    VALID_FOCUS_MODES,
    VALID_GRID_ICON_SIZES,
    VALID_PANEL_PX,
    VALID_VIEW_MODES,
    ServerSettings,
    UserSettings,
)

if TYPE_CHECKING:
    # The accessors below are generated dynamically by the loop at the
    # bottom of this module (``_SETTING_SPECS`` + ``make_accessors``).
    # Declare their signatures here so static type-checkers can resolve
    # ``vtsearch.settings.get_<key>()`` / ``set_<key>()`` calls from
    # other modules. Keep this list in sync with ``_SETTING_SPECS`` and
    # the per-side factory invocations below.

    def get_volume() -> float: ...
    def set_volume(value: float) -> None: ...
    def get_inclusion() -> int: ...
    def set_inclusion(value: int) -> None: ...
    def get_theme() -> str: ...
    def set_theme(value: str) -> None: ...
    def get_enrich_descriptions() -> bool: ...
    def set_enrich_descriptions(value: bool) -> None: ...
    def get_safe_thresholds() -> bool: ...
    def set_safe_thresholds(value: bool) -> None: ...
    def get_calibrate_count() -> int: ...
    def set_calibrate_count(value: int) -> None: ...
    def get_calibration_fraction() -> float: ...
    def set_calibration_fraction(value: float) -> None: ...
    def get_audio_playing() -> bool: ...
    def set_audio_playing(value: bool) -> None: ...
    def get_swipe_animation() -> bool: ...
    def set_swipe_animation(value: bool) -> None: ...
    def get_show_metadata() -> bool: ...
    def set_show_metadata(value: bool) -> None: ...
    def get_label_hint_dismissed() -> bool: ...
    def set_label_hint_dismissed(value: bool) -> None: ...
    def get_autopilot_enabled() -> bool: ...
    def set_autopilot_enabled(value: bool) -> None: ...
    def get_hide_autopilot() -> bool: ...
    def set_hide_autopilot(value: bool) -> None: ...
    def get_enable_achievements() -> bool: ...
    def set_enable_achievements(value: bool) -> None: ...
    def get_browse_panel_width() -> int: ...
    def set_browse_panel_width(value: int) -> None: ...
    def get_browse_bin_shape() -> dict[str, str]: ...
    def set_browse_bin_shape(value: dict[str, str]) -> None: ...
    def get_browse_colormap() -> dict[str, str]: ...
    def set_browse_colormap(value: dict[str, str]) -> None: ...
    def get_browse_icon_size() -> dict[str, str]: ...
    def set_browse_icon_size(value: dict[str, str]) -> None: ...
    def get_browse_thumbnail_border() -> dict[str, int]: ...
    def set_browse_thumbnail_border(value: dict[str, int]) -> None: ...
    def get_browse_compact() -> dict[str, bool]: ...
    def set_browse_compact(value: dict[str, bool]) -> None: ...
    def get_autopilot_top_greens() -> int: ...
    def set_autopilot_top_greens(value: int) -> None: ...
    def get_autopilot_hard_reds() -> int: ...
    def set_autopilot_hard_reds(value: int) -> None: ...
    def get_autopilot_resort_interval() -> int: ...
    def set_autopilot_resort_interval(value: int) -> None: ...
    def get_autopilot_goal_diversity() -> int: ...
    def set_autopilot_goal_diversity(value: int) -> None: ...
    def get_max_concurrent_dataset_downloads() -> int: ...
    def set_max_concurrent_dataset_downloads(value: int) -> None: ...
    def get_max_concurrent_dataset_embeddings() -> int: ...
    def set_max_concurrent_dataset_embeddings(value: int) -> None: ...
    def get_dataset_max_age_days() -> int | None: ...
    def set_dataset_max_age_days(value: int | None) -> None: ...

    # Per-side accessors generated by ``_make_per_side_setting``.
    def get_view_mode_left() -> dict[str, str]: ...
    def get_view_mode_right() -> dict[str, str]: ...
    def set_view_mode_left(value: dict[str, str] | str) -> None: ...
    def set_view_mode_right(value: dict[str, str] | str) -> None: ...
    def get_grid_icon_size_left() -> dict[str, str]: ...
    def get_grid_icon_size_right() -> dict[str, str]: ...
    def set_grid_icon_size_left(value: dict[str, str] | str) -> None: ...
    def set_grid_icon_size_right(value: dict[str, str] | str) -> None: ...
    def get_focus_mode_left() -> dict[str, str]: ...
    def get_focus_mode_right() -> dict[str, str]: ...
    def set_focus_mode_left(value: dict[str, str] | str) -> None: ...
    def set_focus_mode_right(value: dict[str, str] | str) -> None: ...
    def get_panel_pct_left() -> dict[str, int]: ...
    def get_panel_pct_right() -> dict[str, int]: ...
    def set_panel_pct_left(value: dict[str, int] | int | float) -> None: ...
    def set_panel_pct_right(value: dict[str, int] | int | float) -> None: ...

    def get_last_embedder_per_media_type() -> dict[str, str]: ...
    def set_last_embedder_per_media_type(value: dict[str, str]) -> None: ...

    def get_import_defaults_by_media_type() -> dict[str, dict[str, Any]]: ...
    def set_import_defaults_by_media_type(value: dict[str, dict[str, Any]]) -> None: ...

    def get_solo_media_type() -> str | None: ...
    def set_solo_media_type(value: str | None) -> None: ...
    def get_solo_media_type_explicit() -> bool: ...
    def set_solo_media_type_explicit(value: bool) -> None: ...

    def get_solo_embedder_per_media_type() -> dict[str, str]: ...
    def set_solo_embedder_per_media_type(value: dict[str, str]) -> None: ...

    def get_recent_sessions() -> list[dict[str, Any]]: ...
    def set_recent_sessions(value: list[dict[str, Any]]) -> None: ...

    def get_hidden_plugins() -> dict[str, list[str]]: ...
    def set_hidden_plugins(value: dict[str, list[str]]) -> None: ...


logger = logging.getLogger(__name__)

#: Path to the server-tier settings file. Tests monkey-patch this; the CLI
#: ``set_settings_path()`` helper also points it at a different file.
SETTINGS_PATH: Path = DATA_DIR / "settings.json"

#: Process-level fallback for the per-user ``solo_media_type`` setting, set
#: by :func:`set_cli_solo_media_type` from the ``--solo-media-type`` flag
#: in :mod:`app`. ``None`` means "no CLI default"; a user with
#: ``solo_media_type_explicit=False`` will see this value (or ``None``) as
#: their effective solo mediaType. A user who has explicitly set their own
#: value (including explicitly ``None`` for "show everything") overrides
#: this fallback - see :func:`get_effective_solo_media_type`.
_cli_solo_media_type: str | None = None

#: Process-level fallback for the ``hidden_plugins`` server setting, set
#: by :func:`set_cli_hidden_plugins` / :func:`add_cli_hidden_plugin` from
#: the repeatable ``--hide-plugin family:name`` flag in :mod:`app`. Maps
#: a plugin-family id to the set of plugin ``name``s to hide. Merged with
#: the persisted ``hidden_plugins`` server setting at read time - see
#: :func:`get_effective_hidden_plugins`. Empty dict means "no CLI hides".
_cli_hidden_plugins: dict[str, set[str]] = {}

#: Process-level fallback for the per-user
#: ``solo_embedder_per_media_type`` setting, set by
#: :func:`set_cli_solo_embedder` from the (repeatable) ``--solo-embedder``
#: flag in :mod:`app`. Maps ``media_type_id`` → embedder name. Empty means
#: "no CLI default". The resolver :func:`get_effective_solo_embedders`
#: layers per-user entries over this dict (per-key), so a user can override
#: individual mediaTypes without losing the others.
_cli_solo_embedders: dict[str, str] = {}

#: Filename used for the per-user settings file inside
#: ``get_user_data_dir(user)``.
USER_SETTINGS_FILENAME: str = "user_settings.json"

#: Optional override for the directory layout used by per-user settings
#: files. When set, the per-user file resolves to
#: ``_USER_DATA_DIR_OVERRIDE / <username> / USER_SETTINGS_FILENAME``
#: instead of using :func:`vtsearch.auth.get_user_data_dir`. Tests use
#: this to redirect both tiers under a single ``tmp_path`` without
#: monkey-patching the auth module.
_USER_DATA_DIR_OVERRIDE: Path | None = None

# ---------------------------------------------------------------------------
# Defaults, partitioned by tier
# ---------------------------------------------------------------------------

#: Lazy caches for the model-derived defaults dicts.  Instantiating
#: :class:`ServerSettings` fires its pydantic ``default_factory`` callbacks
#: (notably the GPU-aware default for ``max_concurrent_dataset_embeddings``),
#: and that probe imports torch - ~870ms at startup just to pick an int.
#: Defer the instantiation to first read so ``import vtsearch.settings``
#: stays torch-free.
_SERVER_DEFAULTS_CACHE: dict[str, Any] | None = None
_USER_DEFAULTS_CACHE: dict[str, Any] | None = None


def _server_defaults() -> dict[str, Any]:
    global _SERVER_DEFAULTS_CACHE
    if _SERVER_DEFAULTS_CACHE is None:
        _SERVER_DEFAULTS_CACHE = ServerSettings().model_dump()
    return _SERVER_DEFAULTS_CACHE


def _user_defaults() -> dict[str, Any]:
    global _USER_DEFAULTS_CACHE
    if _USER_DEFAULTS_CACHE is None:
        _USER_DEFAULTS_CACHE = UserSettings().model_dump()
    return _USER_DEFAULTS_CACHE


def _all_defaults() -> dict[str, Any]:
    return {**_server_defaults(), **_user_defaults()}


def __getattr__(name: str) -> Any:
    # PEP 562 - expose ``_SERVER_DEFAULTS`` / ``_USER_DEFAULTS`` / ``_DEFAULTS``
    # as attributes for external readers (tests, future callers) without
    # forcing the eager pydantic instantiation at module load.
    if name == "_SERVER_DEFAULTS":
        return _server_defaults()
    if name == "_USER_DEFAULTS":
        return _user_defaults()
    if name == "_DEFAULTS":
        return _all_defaults()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


#: Set of keys that belong to the server tier (everything else is per-user).
#: Reading ``model_fields`` doesn't instantiate the model, so this stays eager.
_SERVER_KEYS: frozenset[str] = frozenset(ServerSettings.model_fields.keys())

#: Per-user keys for which the built-in "default" user reads through to the
#: *server* settings file when the key is absent from its own per-user file.
#: These are the Auto-Find knobs: per-user in multi-user deployments, but the
#: single-user GUI (everyone is "default") and the CLI ``--settings`` flat file
#: still expect a value placed in ``settings.json`` to take effect. The
#: read-through (see :func:`_read_value`) makes that work without the
#: destructive legacy migration moving them out of the server file (see
#: :func:`_maybe_migrate_legacy_settings_locked`, which skips these keys).
_DEFAULT_USER_FALLBACK_KEYS: frozenset[str] = frozenset(
    {"autorun_detectors", "autofind_exporter", "autofind_exporter_field_values"}
)

#: Keys excluded from the "defaults" endpoint (infrastructure settings that
#: should not be reset by the Default button).
_EXCLUDE_FROM_DEFAULTS = {
    "autorun_detectors",
    "autofind_exporter",
    "autofind_exporter_field_values",
    "saved_datasets_dir",
    "detectors_dir",
    "settings_source",
}

#: Keys excluded from source sync export (to avoid circular config).
_EXCLUDE_FROM_SOURCE_EXPORT = {
    "settings_source",
}

# ---------------------------------------------------------------------------
# Caches
# ---------------------------------------------------------------------------

# Server-tier cache (one process-wide dict).
_server_cache: dict[str, Any] | None = None

# Per-user caches keyed by username.
_user_caches: dict[str, dict[str, Any]] = {}


@dataclass
class _UserSyncState:
    """Per-user sync-from-source bookkeeping.

    - ``last_version``: opaque token from :meth:`SettingsSource.peek_version`
      stashed at the last successful sync.  Compared on every read to
      decide whether a re-sync is due.  ``None`` if the source can't
      cheaply check freshness.
    - ``last_check_monotonic``: :func:`time.monotonic` of the last peek.
      Used to rate-limit ``peek_version`` calls so a hot read path doesn't
      stat the source file on every ``get_volume()``.
    - ``last_sync_succeeded``: ``False`` means the user has never been
      successfully synced this process lifetime (or the last attempt
      failed).  A transient source failure no longer permanently locks
      the user out of sync - the slow-path retries (rate-limited) until
      it succeeds.
    - ``dirty_keys``: keys the user has set locally since the last
      successful :func:`_sync_to_source`.  An auto re-sync (from a
      version-bump on the source) skips these keys so a freshly clicked
      local toggle isn't silently overwritten by an upstream value.
      Cleared whenever ``_sync_to_source`` succeeds (because the source
      then matches local) or when a manual :func:`sync_from_settings_source`
      runs (explicit user pull).
    """

    last_version: Any = None
    last_check_monotonic: float = 0.0
    last_sync_succeeded: bool = False
    dirty_keys: set[str] = field(default_factory=set)


# Per-user sync bookkeeping.  Replaces the old ``_synced_users: set[str]``,
# which couldn't distinguish "never synced" from "synced ages ago" or
# "tried once and failed."
_sync_state: dict[str, _UserSyncState] = {}

# One-shot legacy-migration guard.
_legacy_migrated: bool = False

# Reentrant lock covering both tiers' caches, the syncing flag, and
# ``_sync_state``.  Not held while running the actual sync I/O.
_settings_lock = threading.RLock()

# Per-user reentrant locks wrapping the sync-from-source critical
# section.  Acquiring this means "I'm responsible for this user's
# sync-from-source pass right now"; another thread for the same user
# blocks until we're done and then sees the freshly-applied cache.
# Reentrant so a setter called from inside ``_apply_settings`` (which
# routes back through ``_ensure_user_loaded``) doesn't self-deadlock.
_user_sync_locks: dict[str, threading.RLock] = {}
_user_sync_locks_guard = threading.Lock()

# Rate-limit window for the ``peek_version`` freshness probe.  Settings
# reads happen in hot paths (``before_request``, every accessor); we
# don't want to stat the source file on every one.  The first read in a
# window does the probe; subsequent reads inside the window short-circuit
# back to the local cache.
_FRESHNESS_CHECK_INTERVAL = 1.0

# Set of usernames currently being imported from their settings_source.
# A per-user save that fires while the user is in this set skips
# ``_sync_to_source`` so the import isn't immediately re-exported.  Also
# acts as a recursion guard for ``_ensure_user_loaded``: a setter called
# from inside ``_apply_settings`` re-enters the function but must skip
# the sync path.
_syncing: set[str] = set()


def _per_user_sync_lock(username: str) -> threading.RLock:
    """Return (creating if needed) the sync RLock for *username*."""
    with _user_sync_locks_guard:
        lock = _user_sync_locks.get(username)
        if lock is None:
            lock = threading.RLock()
            _user_sync_locks[username] = lock
        return lock


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def _server_settings_path() -> Path:
    return SETTINGS_PATH


def _user_settings_path(username: str) -> Path:
    """Return the per-user settings file path for *username*."""
    if _USER_DATA_DIR_OVERRIDE is not None:
        return _USER_DATA_DIR_OVERRIDE / username / USER_SETTINGS_FILENAME
    from vtsearch.auth import get_user_data_dir

    return get_user_data_dir(username) / USER_SETTINGS_FILENAME


# ---------------------------------------------------------------------------
# File I/O
# ---------------------------------------------------------------------------


def _load_path(path: Path) -> dict[str, Any]:
    """Read settings from *path*, returning ``{}`` on any failure."""
    if path.exists():
        try:
            text = path.read_text(encoding="utf-8")
            data = json.loads(text)
            if isinstance(data, dict):
                return data
        except Exception as exc:
            logger.warning("Failed to read settings file %s: %s", path, exc)
    return {}


def _atomic_write(path: Path, data: dict[str, Any]) -> None:
    """Write *data* to *path* via a per-writer temp file + rename.

    The temp filename embeds PID + a UUID so two processes writing to the
    same target can't truncate each other's in-flight temp file. The
    final ``os.replace`` is atomic on POSIX, so a concurrent reader
    always sees either the pre- or post-write content, never a partial
    write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp")
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(json.dumps(data, indent=2) + "\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except Exception:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp)
        raise


# Per-path in-process locks. Used in two ways:
# 1. As a fallback when ``fcntl`` is unavailable (Windows).
# 2. Held in addition to the cross-process flock so that, within a single
#    process, multiple threads serialise on the same path without
#    repeatedly re-entering the kernel.
_path_locks: dict[str, threading.Lock] = {}
_path_locks_guard = threading.Lock()


def _path_lock_for(path: Path) -> threading.Lock:
    key = str(path.resolve()) if path.exists() else str(path)
    with _path_locks_guard:
        lock = _path_locks.get(key)
        if lock is None:
            lock = threading.Lock()
            _path_locks[key] = lock
        return lock


@contextlib.contextmanager
def _file_lock(path: Path):
    """Acquire an exclusive cross-process lock for *path*.

    The lock is taken on a sibling ``<path>.lock`` file rather than on
    the data file itself, because ``_atomic_write`` replaces the data
    file's inode via ``os.replace`` - any fd held against the old inode
    would be useless. The sibling lock file's inode is stable.

    The lock is released automatically if the process exits (POSIX
    flock semantics), so there are no zombie locks after crashes.

    On Windows (``fcntl`` unavailable) the in-process lock alone is
    used; cross-process protection degrades silently. VTSearch is
    deployed on Linux containers, so this only affects the rare
    Windows-dev case where multiple processes shouldn't be writing
    the same settings file anyway.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    in_proc = _path_lock_for(path)
    in_proc.acquire()
    fd: int | None = None
    fcntl_mod = _fcntl  # snapshot so the narrowed binding survives the yield
    if fcntl_mod is not None:
        lock_path = path.with_name(path.name + ".lock")
        try:
            fd = os.open(str(lock_path), os.O_WRONLY | os.O_CREAT, 0o600)
            fcntl_mod.flock(fd, fcntl_mod.LOCK_EX)
        except OSError as exc:
            logger.warning("Could not acquire file lock on %s: %s", lock_path, exc)
            if fd is not None:
                with contextlib.suppress(OSError):
                    os.close(fd)
                fd = None
    try:
        yield
    finally:
        if fd is not None and fcntl_mod is not None:
            try:
                fcntl_mod.flock(fd, fcntl_mod.LOCK_UN)
            finally:
                with contextlib.suppress(OSError):
                    os.close(fd)
        in_proc.release()


# ---------------------------------------------------------------------------
# Cache loaders
# ---------------------------------------------------------------------------


def _ensure_server_loaded() -> dict[str, Any]:
    """Load the server-tier cache on first access and migrate legacy keys."""
    global _server_cache
    with _settings_lock:
        if _server_cache is None:
            _server_cache = _load_path(_server_settings_path())
            _maybe_migrate_legacy_settings_locked()
        return _server_cache


def _ensure_user_loaded(username: str) -> dict[str, Any]:
    """Load *username*'s per-user cache on first access and reconcile with the source.

    Fast path: take ``_settings_lock`` briefly, hydrate the local cache
    if needed, and return immediately when no sync work is due (no
    source configured, freshness window still valid, or we're already
    inside an import for this user).

    Slow path: take the per-user sync RLock so the actual ``peek_version``
    + ``load`` + ``_apply_settings`` work happens serially for the same
    user, and concurrent readers see the post-sync cache when they
    acquire the lock.  Without this lock the previous design had a
    TOCTOU race: thread A set the "synced" marker before running the
    sync, so a concurrent thread B saw the marker and returned the
    pre-sync local cache.
    """
    with _settings_lock:
        cache = _user_caches.get(username)
        if cache is None:
            # Make sure server tier is loaded (and legacy migration has run)
            # before we materialise a fresh user cache, otherwise the legacy
            # migration step might not see this user yet.
            _ensure_server_loaded()
            cache = _user_caches.get(username)
            if cache is None:
                cache = _load_path(_user_settings_path(username))
                _user_caches[username] = cache
        # Re-entrance guard: a setter inside ``_apply_settings`` re-enters
        # this function while the outer call holds the sync lock.  Skip
        # the sync path so we don't recurse or fire another peek probe.
        if username in _syncing:
            return cache
        cfg = cache.get("settings_source")
        has_source = isinstance(cfg, dict) and bool(cfg.get("source_name"))
        if not has_source:
            return cache
        state = _sync_state.get(username)
        if state is not None and state.last_sync_succeeded:
            now = time.monotonic()
            if now - state.last_check_monotonic < _FRESHNESS_CHECK_INTERVAL:
                # Hot path: a recent successful sync exists and we're
                # inside the rate-limit window.  No probe, no lock.
                return cache

    sync_lock = _per_user_sync_lock(username)
    with sync_lock:
        if _needs_sync_from_source(username):
            _run_sync_from_source(username)

    return _user_caches[username]


def _needs_sync_from_source(username: str) -> bool:
    """Decide whether a sync-from-source pass is due for *username*.

    Called with the per-user sync lock held (so the decision and the
    subsequent sync are atomic with respect to other threads on the
    same user).  A sync is due when:

    1. We've never attempted one this process lifetime, OR
    2. The last attempt failed and the rate-limit window has elapsed
       (so a transient source outage no longer permanently locks
       the user out of sync - old ``_synced_users`` did exactly that), OR
    3. A previous attempt succeeded but the source's
       :meth:`SettingsSource.peek_version` token has changed since
       (source file rewritten by another process, hand-edited, etc.).

    Refreshes ``last_check_monotonic`` on the no-sync paths so the
    freshness probe is rate-limited even when state is being mutated.
    """
    with _settings_lock:
        state = _sync_state.get(username)
        cache_cfg = _user_caches.get(username, {}).get("settings_source")
    if not isinstance(cache_cfg, dict) or not cache_cfg.get("source_name"):
        return False

    now = time.monotonic()

    if state is None or state.last_check_monotonic == 0.0:
        # No state, or state exists only because a setter populated it
        # via ``_mark_user_keys_dirty`` before we'd ever talked to the
        # source.  Either way: first sync attempt is due.
        return True

    if not state.last_sync_succeeded:
        # Rate-limited retry after a failure.
        return (now - state.last_check_monotonic) >= _FRESHNESS_CHECK_INTERVAL

    # Last attempt succeeded.  If we're still inside the freshness
    # window, skip (the fast path in ``_ensure_user_loaded`` usually
    # handles this; keep the check here in case the slow path was
    # entered via a different code route).
    if (now - state.last_check_monotonic) < _FRESHNESS_CHECK_INTERVAL:
        return False

    # Window elapsed - cheap probe to detect upstream changes.
    from vtsearch.settings_io.sources import get_settings_source

    source = get_settings_source(cache_cfg["source_name"])
    if source is None:
        return False
    field_values = cache_cfg.get("field_values", {})
    try:
        current_version = source.peek_version(field_values)
    except Exception:
        # Transient peek failure - back off until next window, keep
        # serving the local cache.
        with _settings_lock:
            s = _sync_state.get(username)
            if s is not None:
                s.last_check_monotonic = now
        return False

    if current_version is None or current_version == state.last_version:
        # Source can't cheaply check, or unchanged since last sync.
        with _settings_lock:
            s = _sync_state.get(username)
            if s is not None:
                s.last_check_monotonic = now
        return False

    return True


def _run_sync_from_source(username: str) -> None:
    """Pull settings from *username*'s configured source and apply them.

    Called with the per-user sync lock held.  Respects ``dirty_keys``:
    keys the user has set locally since the last successful
    ``_sync_to_source`` are skipped so a clicked-toggle isn't silently
    overwritten by an upstream value.

    On success: stash the new ``peek_version`` token, mark the user as
    successfully synced, and refresh the freshness-check timestamp.
    On failure: log the error and refresh only the check timestamp
    (``last_sync_succeeded`` stays ``False``) so the slow path retries
    once the rate-limit window elapses.
    """
    with _settings_lock:
        cache_cfg = _user_caches.get(username, {}).get("settings_source")
        state = _sync_state.setdefault(username, _UserSyncState())
        dirty_snapshot = set(state.dirty_keys)
    if not isinstance(cache_cfg, dict) or not cache_cfg.get("source_name"):
        return

    from vtsearch.settings_io.sources import get_settings_source

    source = get_settings_source(cache_cfg["source_name"])
    if source is None:
        logger.warning("Unknown settings source: %s", cache_cfg["source_name"])
        return

    field_values = cache_cfg.get("field_values", {})
    new_version: Any = None
    try:
        new_version = source.peek_version(field_values)
    except Exception:
        new_version = None

    try:
        imported = source.load(field_values)
    except Exception as exc:
        logger.exception("Failed to load from settings source for %s: %s", username, exc)
        with _settings_lock:
            state = _sync_state.setdefault(username, _UserSyncState())
            state.last_check_monotonic = time.monotonic()
            # Leave last_sync_succeeded as-is: a transient failure after
            # a previous success must not erase the success flag (the
            # local cache is still valid).
        return

    if imported:
        with _settings_lock:
            _syncing.add(username)
        try:
            _apply_settings(imported, skip_keys=dirty_snapshot)
        finally:
            with _settings_lock:
                _syncing.discard(username)

    with _settings_lock:
        state = _sync_state.setdefault(username, _UserSyncState())
        state.last_version = new_version
        state.last_check_monotonic = time.monotonic()
        state.last_sync_succeeded = True
        # dirty_keys preserved across an auto re-sync - the user's local
        # edits stay protected until an explicit ``_sync_to_source`` push
        # confirms the source matches local (which clears them) or a
        # manual POST sync clears them on purpose.


def _maybe_migrate_legacy_settings_locked() -> None:
    """Move per-user keys from a legacy ``data/settings.json`` into the
    default user's per-user file (one-shot, idempotent).

    Called from :func:`_ensure_server_loaded` with the settings lock held.
    """
    global _legacy_migrated
    if _legacy_migrated:
        return
    _legacy_migrated = True
    assert _server_cache is not None
    # ``_DEFAULT_USER_FALLBACK_KEYS`` legitimately live in the server file (the
    # default user reads through to them), so they are NOT "orphaned per-user"
    # keys; leave them in place rather than moving them into the default user's
    # file (which would also rewrite a CLI ``--settings`` file under the user).
    legacy_user_entries = {
        k: v for k, v in _server_cache.items() if k not in _SERVER_KEYS and k not in _DEFAULT_USER_FALLBACK_KEYS
    }
    if not legacy_user_entries:
        return

    # Migrate into the "default" user's file. The default user is the one
    # the single-user provider returns, and is also the safe target for
    # multi-user upgrades (admins can copy it into other users' files).
    default_user = "default"
    user_path = _user_settings_path(default_user)
    if user_path.exists():
        existing = _load_path(user_path)
        # Existing per-user values win - never clobber a real user file.
        merged: dict[str, Any] = {**legacy_user_entries, **existing}
    else:
        merged = dict(legacy_user_entries)
    try:
        _atomic_write(user_path, merged)
    except Exception as exc:
        logger.warning("Legacy settings migration to %s failed: %s", user_path, exc)
        return

    # Build the server-tier shape first; a failure here must not pop the
    # in-memory cache, or _server_cache and disk would silently diverge. Keep
    # the default-user fallback keys in the server file (they are read through
    # there, not migrated out).
    new_server = {k: v for k, v in _server_cache.items() if k in _SERVER_KEYS or k in _DEFAULT_USER_FALLBACK_KEYS}
    try:
        _atomic_write(_server_settings_path(), new_server)
    except Exception as exc:
        logger.warning("Failed to rewrite server settings after legacy migration: %s", exc)
        return
    for k in list(_server_cache.keys()):
        if k not in _SERVER_KEYS and k not in _DEFAULT_USER_FALLBACK_KEYS:
            _server_cache.pop(k, None)

    # Refresh the default user's cache if it was already materialised
    # (unlikely, since this runs from _ensure_server_loaded, but safe).
    _user_caches[default_user] = _load_path(user_path)
    logger.info(
        "Migrated %d legacy per-user setting(s) from %s into %s",
        len(legacy_user_entries),
        _server_settings_path(),
        user_path,
    )


# ---------------------------------------------------------------------------
# Save helpers
# ---------------------------------------------------------------------------


def _mutate_server_locked(mutator) -> None:
    """Apply *mutator* to a fresh-from-disk server cache, atomically.

    Acquires the cross-process file lock, re-reads ``data/settings.json``
    so any changes a sibling process made since this process loaded are
    picked up, runs ``mutator(cache)`` to mutate the dict in place, then
    atomically writes the result back. This is the only correct way to
    mutate a multi-writer settings file from a Python process.

    The legacy migration is left to ``_ensure_server_loaded`` and never
    fires from inside the lock - by the time any setter runs the cache
    has been loaded at least once.

    File I/O (``_load_path``, ``_atomic_write``) runs under the
    cross-process file lock only; ``_settings_lock`` is acquired briefly
    at the end just to swap the in-memory cache, so a slow local fsync
    (NFS, full disk, hung disk controller) can't stall unrelated
    settings reads - see H29 in ``docs/plans/logical-bug-audit.md``.
    """
    global _server_cache
    path = _server_settings_path()
    with _file_lock(path):
        fresh = _load_path(path)
        mutator(fresh)
        _atomic_write(path, fresh)
        with _settings_lock:
            _server_cache = fresh


def _mutate_user_locked(username: str, mutator) -> dict[str, Any] | None:
    """Apply *mutator* to a fresh-from-disk per-user cache, atomically.

    Returns a snapshot of the cache after the mutation, intended for
    ``_sync_to_source`` which is invoked **outside** the file lock so a
    slow sync target (NFS, webhook) can't block other settings writes.
    Returns ``None`` if the cache should not be synced (i.e. we are
    currently importing from the source).

    Like :func:`_mutate_server_locked`, file I/O runs under the
    cross-process file lock only; ``_settings_lock`` is acquired briefly
    at the end just to swap the in-memory cache and read the ``_syncing``
    flag.
    """
    path = _user_settings_path(username)
    with _file_lock(path):
        fresh = _load_path(path)
        mutator(fresh)
        _atomic_write(path, fresh)
        with _settings_lock:
            _user_caches[username] = fresh
            if username in _syncing:
                return None
            return dict(fresh)


def mutate_user(mutator) -> None:
    """Atomically read-modify-write the current user's settings file.

    The on-disk file is locked across processes, re-read fresh,
    *mutator(cache)* runs to mutate the loaded dict in place, and the
    result is written back atomically. Use this whenever you need to
    update a nested structure (counters, list appends, dict merges) -
    a plain ``set_*`` call only round-trips the top-level key correctly
    if you replace it wholesale, but ``mutate_user`` is correct for
    any in-place change.

    Triggers ``_sync_to_source`` after the lock is released (so a slow
    sync target can't block other settings writes).
    """
    from vtsearch.auth import get_current_user

    username = get_current_user()
    _ensure_user_loaded(username)
    sync_data = _mutate_user_locked(username, mutator)
    if sync_data is not None:
        # ``mutate_user`` can change arbitrary top-level keys; mark
        # every exportable key dirty so an auto re-sync between now
        # and the ``_sync_to_source`` push doesn't clobber the mutation.
        _mark_user_keys_dirty(username, [k for k in sync_data if k not in _EXCLUDE_FROM_SOURCE_EXPORT])
        _sync_to_source(username, sync_data)


# ---------------------------------------------------------------------------
# Low-level value get/set used by accessor factories
# ---------------------------------------------------------------------------


def _read_value(key: str) -> Any:
    """Return the raw stored value for *key* (or its default).

    Routes to the server tier or the current user's tier based on *key*.
    The caller is responsible for casting/coercion.
    """
    if key in _SERVER_KEYS:
        return _ensure_server_loaded().get(key, _server_defaults()[key])
    from vtsearch.auth import get_current_user

    username = get_current_user()
    user_cache = _ensure_user_loaded(username)
    if key in user_cache:
        return user_cache[key]
    # Default-user read-through: the single-user GUI and the CLI ``--settings``
    # flat file carry these Auto-Find keys in the server settings file. Honor
    # them for the built-in "default" user when not set in its own file, so
    # those workflows keep working without making the setting truly server-wide.
    if username == "default" and key in _DEFAULT_USER_FALLBACK_KEYS:
        server_cache = _ensure_server_loaded()
        if key in server_cache:
            return server_cache[key]
    return _user_defaults().get(key)


def _write_value(key: str, value: Any) -> None:
    """Persist *value* for *key*, routing to the correct tier.

    Each call is a single read-modify-write under the cross-process
    file lock: the on-disk file is re-read, *key* is replaced, the
    merged dict is written back, then the in-memory cache is refreshed
    to match. This means two processes setting *different* keys on the
    same user no longer clobber each other.
    """
    if key in _SERVER_KEYS:
        _ensure_server_loaded()  # one-shot legacy migration
        _mutate_server_locked(lambda c: c.__setitem__(key, value))
        return
    from vtsearch.auth import get_current_user

    username = get_current_user()
    _ensure_user_loaded(username)  # reconciles with source if due
    sync_data = _mutate_user_locked(username, lambda c: c.__setitem__(key, value))
    if sync_data is not None:
        # User-initiated write (not from an in-progress import).  Mark
        # this key dirty so an auto re-sync running between now and the
        # ``_sync_to_source`` push leaves it alone - the source push
        # below clears the dirty flag again once it succeeds.
        if key not in _EXCLUDE_FROM_SOURCE_EXPORT:
            _mark_user_keys_dirty(username, [key])
        _sync_to_source(username, sync_data)


def _mark_user_keys_dirty(username: str, keys) -> None:
    """Add *keys* to the user's ``dirty_keys`` set."""
    if not keys:
        return
    with _settings_lock:
        state = _sync_state.setdefault(username, _UserSyncState())
        state.dirty_keys.update(keys)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_defaults() -> dict[str, Any]:
    """Return a copy of the default settings (excluding infrastructure keys)."""
    result = {k: v for k, v in _all_defaults().items() if k not in _EXCLUDE_FROM_DEFAULTS}
    valid_types = _valid_media_types()
    result["view_mode_left"] = {tid: _VIEW_MODE_DEFAULTS["left"] for tid in valid_types}
    result["view_mode_right"] = {tid: _VIEW_MODE_DEFAULTS["right"] for tid in valid_types}
    result["grid_icon_size_left"] = {tid: _GRID_ICON_SIZE_DEFAULT for tid in valid_types}
    result["grid_icon_size_right"] = {tid: _GRID_ICON_SIZE_DEFAULT for tid in valid_types}
    result["focus_mode_left"] = {tid: _FOCUS_MODE_DEFAULTS["left"] for tid in valid_types}
    result["focus_mode_right"] = {tid: _FOCUS_MODE_DEFAULTS["right"] for tid in valid_types}
    result["panel_pct_left"] = {tid: _PANEL_PX_DEFAULTS["left"] for tid in valid_types}
    result["panel_pct_right"] = {tid: _PANEL_PX_DEFAULTS["right"] for tid in valid_types}
    return result


def get_user_settings() -> dict[str, Any]:
    """Return the current user's per-user settings (with defaults filled in).

    Used by the settings-export route and the per-user sync source so an
    export only carries this user's preferences - not the shared
    server-tier infrastructure keys (``saved_datasets_dir``,
    ``autoload_media_embedders`` etc.) and not other users' files.
    """
    from vtsearch.auth import get_current_user

    username = get_current_user()
    # ``_ensure_user_loaded`` may trigger sync-from-source which calls
    # setters that acquire ``_file_lock``. Calling it outside
    # ``_settings_lock`` keeps the canonical lock order
    # (file_lock → settings_lock) and avoids an AB-BA deadlock with
    # concurrent writers.
    _ensure_user_loaded(username)
    with _settings_lock:
        user_copy = dict(_user_caches.get(username, {}))
    result = dict(_user_defaults())
    result.update(user_copy)
    result["view_mode_left"] = get_view_mode_left()
    result["view_mode_right"] = get_view_mode_right()
    result["grid_icon_size_left"] = get_grid_icon_size_left()
    result["grid_icon_size_right"] = get_grid_icon_size_right()
    result["focus_mode_left"] = get_focus_mode_left()
    result["focus_mode_right"] = get_focus_mode_right()
    result["panel_pct_left"] = get_panel_pct_left()
    result["panel_pct_right"] = get_panel_pct_right()
    return result


def get_all() -> dict[str, Any]:
    """Return the merged settings dict for the current user.

    Combines the server-tier defaults+overrides with the current user's
    per-user defaults+overrides. The per-side view-mode dicts are
    returned in expanded (per-media-type) form.
    """
    from vtsearch.auth import get_current_user

    username = get_current_user()
    _ensure_server_loaded()
    _ensure_user_loaded(username)
    with _settings_lock:
        server_copy = dict(_server_cache or {})
        user_copy = dict(_user_caches.get(username, {}))
    result = dict(_all_defaults())
    result.update(server_copy)
    result.update(user_copy)
    # Always return expanded per-media-type view/focus/panel dicts.
    result["view_mode_left"] = get_view_mode_left()
    result["view_mode_right"] = get_view_mode_right()
    result["grid_icon_size_left"] = get_grid_icon_size_left()
    result["grid_icon_size_right"] = get_grid_icon_size_right()
    result["focus_mode_left"] = get_focus_mode_left()
    result["focus_mode_right"] = get_focus_mode_right()
    result["panel_pct_left"] = get_panel_pct_left()
    result["panel_pct_right"] = get_panel_pct_right()
    # Auto-Find keys go through their accessors so the default-user read-through
    # (and per-user isolation for named users) is applied consistently: the
    # plain ``result.update(server_copy)`` above would otherwise leak a legacy
    # server-file autorun list to every named user.
    result["autorun_detectors"] = get_autorun_detectors()
    result["autofind_exporter"] = get_autofind_exporter()  # noqa: F821  # autogen'd accessor
    result["autofind_exporter_field_values"] = get_autofind_exporter_field_values()  # noqa: F821  # autogen'd accessor
    return result


# -------------------------------------------------------------------
# Pydantic-driven generation of simple get_<key> / set_<key> pairs.
#
# Each :class:`UserSettings` / :class:`ServerSettings` field becomes a
# pair of module-level accessors. Validation (clamping, one-of) lives
# on the model; the shims below only marshal values between the cache
# dict and ``model_validate({key: value})``.
# -------------------------------------------------------------------


def _validate_field(model: type, key: str, value: Any) -> Any:
    """Run *value* through *model*'s validator for *key* and return the result.

    Uses ``model_validate`` with a single-key dict so per-field
    ``BeforeValidator`` clamps and enum checks fire as if the value had
    been loaded from disk. A :class:`pydantic.ValidationError` is
    surfaced as :class:`ValueError` with a compact message - matches the
    error shape callers expect from the legacy spec-driven setters.
    """
    try:
        validated = model.model_validate({key: value}).model_dump()
    except ValidationError as exc:
        first = exc.errors()[0] if exc.errors() else {"msg": str(exc)}
        raise ValueError(f"Invalid {key}: {first.get('msg', exc)}") from None
    return validated[key]


def _make_scalar_accessors(model: type, key: str):
    def getter():
        with _settings_lock:
            raw = _read_value(key)
        try:
            return _validate_field(model, key, raw)
        except ValueError:
            # Corrupt disk value - fall back to the default so callers
            # never see partially-typed garbage.
            return model.model_fields[key].get_default(call_default_factory=True)

    def setter(value):
        # Lock acquisition is delegated to ``_write_value`` →
        # ``_mutate_*_locked``, which takes ``_file_lock`` first and
        # then ``_settings_lock``. Acquiring ``_settings_lock`` here
        # would invert the order and risk an AB-BA deadlock with paths
        # that enter ``_mutate_*_locked`` directly.
        coerced = _validate_field(model, key, value)
        _write_value(key, coerced)

    getter.__name__ = f"get_{key}"
    setter.__name__ = f"set_{key}"
    return getter, setter


# Generate accessors for every field in both models. The ``autorun_detectors``
# key on ServerSettings is excluded because it has hand-written accessors
# below with extra semantics (dedupe, add/remove/is_).
_SKIP_AUTOGEN = {"autorun_detectors", "saved_datasets_dir", "detectors_dir"}
_PER_SIDE_KEYS = {
    "view_mode_left",
    "view_mode_right",
    "grid_icon_size_left",
    "grid_icon_size_right",
    "focus_mode_left",
    "focus_mode_right",
    "panel_pct_left",
    "panel_pct_right",
}

for _model in (ServerSettings, UserSettings):
    for _field_name in _model.model_fields:
        if _field_name in _SKIP_AUTOGEN or _field_name in _PER_SIDE_KEYS:
            continue
        _g, _s = _make_scalar_accessors(_model, _field_name)
        globals()[f"get_{_field_name}"] = _g
        globals()[f"set_{_field_name}"] = _s

del _model, _field_name, _g, _s


# -------------------------------------------------------------------
# Per-media-type per-side settings
#
# These eight settings (``view_mode_{left,right}``,
# ``grid_icon_size_{left,right}``, ``focus_mode_{left,right}``,
# ``panel_pct_{left,right}``) store a ``{media_type_id: value}`` dict.
# Their validation rules differ from the simple settings in two ways:
#
# 1. The set of valid media-type IDs is resolved dynamically from
#    :func:`vtscore.media.all_type_ids` (plugins may register more).
# 2. ``panel_pct_*`` raises on out-of-range writes but clamps on reads
#    (the disk value can become invalid via direct file edits).
#
# We keep a small shim layer that delegates per-element validation to
# the Pydantic models defined in :mod:`vtsearch.settings_models`.
# -------------------------------------------------------------------

_VIEW_MODE_DEFAULTS: dict[str, str] = {"left": "list", "right": "grid"}
_GRID_ICON_SIZE_DEFAULT: str = "M"
_FOCUS_MODE_DEFAULTS: dict[str, str] = {"left": "click", "right": "click"}
_PANEL_PX_DEFAULTS: dict[str, int] = {"left": 260, "right": 300}


def _valid_media_types() -> tuple[str, ...]:
    """Return valid media type IDs from the media registry."""
    from vtscore.media import all_type_ids

    return tuple(all_type_ids())


def _make_per_side_setting(  # noqa: C901
    key_base: str,
    defaults: dict[str, Any],
    *,
    normalize=None,
    value_type: str = "str",
    valid_values: tuple[str, ...] | None = None,
):
    """Build ``get_{base}_left``/``_right`` and ``set_{base}_left``/``_right``.

    *normalize* is applied to string values on read and write (e.g.
    :func:`str.upper`). *valid_values* enables enum membership checks
    for string types. For ``value_type="int"`` the value is clamped to
    :data:`VALID_PANEL_PX` on read and raises on out-of-range writes.
    """
    lo_hi = VALID_PANEL_PX if value_type == "int" else None

    def _validate_entry(v, key: str, tid: str | None = None):
        if value_type == "str":
            if normalize is not None and isinstance(v, str):
                v = normalize(v)
            if valid_values is not None and v not in valid_values:
                label = f"{key} value for {tid}" if tid else key
                raise ValueError(f"Invalid {label}: {v!r}")
            return v
        # int (panel_pct): raise on out-of-range writes
        lo, hi = lo_hi  # type: ignore[misc]
        try:
            v = int(round(float(v)))
        except (ValueError, TypeError):
            label = f"{key} value for {tid}" if tid else key
            raise ValueError(f"Invalid {label}: {v!r}") from None
        if not (lo <= v <= hi):
            label = f"{key} value for {tid}" if tid else key
            raise ValueError(f"Invalid {label}: {v} (must be between {lo} and {hi})")
        return v

    def _get_dict(key: str) -> dict[str, Any]:
        side = key[len(key_base) + 1 :]
        default_val = defaults.get(side, next(iter(defaults.values())))
        with _settings_lock:
            raw = _read_value(key)
        types = _valid_media_types()
        if not isinstance(raw, dict):
            return {tid: default_val for tid in types}

        result: dict[str, Any] = {}
        for tid in types:
            v = raw.get(tid, default_val)
            if normalize is not None and isinstance(v, str):
                v = normalize(v)
            if valid_values is not None and v not in valid_values:
                v = default_val
            elif value_type == "int":
                lo, hi = lo_hi  # type: ignore[misc]
                try:
                    v = max(lo, min(hi, int(round(float(v)))))
                except (ValueError, TypeError):
                    v = default_val
            result[tid] = v
        return result

    def _set_dict(key: str, value) -> None:
        valid_types = _valid_media_types()

        # Scalar expansion: "grid" → {"audio": "grid", "image": "grid", ...}
        if value_type == "str" and isinstance(value, str):
            value = {tid: _validate_entry(value, key) for tid in valid_types}
        elif value_type == "int" and isinstance(value, (int, float)):
            value = {tid: _validate_entry(value, key) for tid in valid_types}

        if not isinstance(value, dict):
            expected = "dict or string" if value_type == "str" else "dict or number"
            raise ValueError(f"{key} must be a {expected}")

        coerced: dict[str, Any] = {}
        for tid, v in value.items():
            if tid not in valid_types:
                raise ValueError(f"Invalid media type: {tid!r}")
            coerced[tid] = _validate_entry(v, key, tid)

        # Locks are taken inside ``_write_value`` in the canonical
        # order (file_lock → settings_lock); see ``_make_scalar_accessors.setter``.
        _write_value(key, coerced)

    def get_left():
        return _get_dict(f"{key_base}_left")

    def get_right():
        return _get_dict(f"{key_base}_right")

    def set_left(value):
        _set_dict(f"{key_base}_left", value)

    def set_right(value):
        _set_dict(f"{key_base}_right", value)

    get_left.__name__ = f"get_{key_base}_left"
    get_right.__name__ = f"get_{key_base}_right"
    set_left.__name__ = f"set_{key_base}_left"
    set_right.__name__ = f"set_{key_base}_right"
    return get_left, get_right, set_left, set_right


get_view_mode_left, get_view_mode_right, set_view_mode_left, set_view_mode_right = _make_per_side_setting(
    "view_mode",
    _VIEW_MODE_DEFAULTS,
    valid_values=VALID_VIEW_MODES,
)

get_grid_icon_size_left, get_grid_icon_size_right, set_grid_icon_size_left, set_grid_icon_size_right = (
    _make_per_side_setting(
        "grid_icon_size",
        {"left": _GRID_ICON_SIZE_DEFAULT, "right": _GRID_ICON_SIZE_DEFAULT},
        valid_values=VALID_GRID_ICON_SIZES,
        normalize=str.upper,
    )
)

get_focus_mode_left, get_focus_mode_right, set_focus_mode_left, set_focus_mode_right = _make_per_side_setting(
    "focus_mode",
    _FOCUS_MODE_DEFAULTS,
    valid_values=VALID_FOCUS_MODES,
)

get_panel_pct_left, get_panel_pct_right, set_panel_pct_left, set_panel_pct_right = _make_per_side_setting(
    "panel_pct",
    _PANEL_PX_DEFAULTS,
    value_type="int",
)


def get_last_embedder_for_media_type(media_type: str) -> str:
    """Return the user's last picked embedder for *media_type*, or ``""``."""
    if not media_type:
        return ""
    raw = get_last_embedder_per_media_type()
    if isinstance(raw, dict):
        value = raw.get(media_type, "")
        if isinstance(value, str):
            return value
    return ""


def set_last_embedder_for_media_type(media_type: str, embedder: str) -> None:
    """Record *embedder* as the user's last pick for *media_type*."""
    if not media_type or not embedder:
        return
    current = get_last_embedder_per_media_type()
    updated = dict(current) if isinstance(current, dict) else {}
    if updated.get(media_type) == embedder:
        return
    updated[media_type] = embedder
    set_last_embedder_per_media_type(updated)


def set_cli_solo_media_type(value: str | None) -> None:
    """Set the process-level fallback for the per-user ``solo_media_type`` setting.

    Called once from ``app.py`` startup when ``--solo-media-type`` is
    passed on the command line. The value is consulted by
    :func:`get_effective_solo_media_type` for any user who has not
    explicitly set their own ``solo_media_type`` via the settings UI.
    Pass ``None`` (or call from a process where ``--solo-media-type`` was
    not passed) to disable the fallback.
    """
    global _cli_solo_media_type
    if value is not None:
        value = value.strip() or None
    _cli_solo_media_type = value


def get_cli_solo_media_type() -> str | None:
    """Return the process-level CLI fallback (``None`` if unset)."""
    return _cli_solo_media_type


def get_effective_solo_media_type() -> str | None:
    """Return the effective solo mediaType for the current user.

    Resolution order:

    1. The user's explicit choice (``solo_media_type`` when
       ``solo_media_type_explicit`` is True), including an explicit
       ``None`` for "show everything".
    2. The process-level CLI fallback set by
       :func:`set_cli_solo_media_type`.
    3. ``None`` (no streamlining - show every mediaType).

    Returns ``None`` to mean "no solo mode active"; any other return
    value is a mediaType id (e.g. ``"image"``) that the UI should lock
    its pickers to.
    """
    if get_solo_media_type_explicit():  # type: ignore[name-defined]  # autogen'd accessor
        explicit = get_solo_media_type()  # type: ignore[name-defined]  # autogen'd accessor
        # Empty string from JSON drift normalises to None.
        if isinstance(explicit, str) and not explicit.strip():
            return None
        return explicit
    return _cli_solo_media_type


def apply_user_solo_media_type(value: str | None) -> None:
    """Persist *value* as the user's solo mediaType choice and flip ``explicit``.

    Used by the settings PUT route so a single UI change updates both
    fields atomically. ``value=None`` (or an empty string) means "show
    everything"; any other string is validated against the media-type
    registry by the route layer before this is called.
    """
    if isinstance(value, str) and not value.strip():
        value = None
    set_solo_media_type(value)  # type: ignore[name-defined]  # autogen'd accessor
    set_solo_media_type_explicit(True)  # type: ignore[name-defined]  # autogen'd accessor


def set_cli_solo_embedder(media_type: str, embedder: str | None) -> None:
    """Set or clear a process-level solo-embedder fallback for *media_type*.

    Called from ``app.py`` startup for each ``--solo-embedder TYPE=EMB``
    pair on the command line. Pass ``embedder=None`` (or an empty
    string) to clear an entry. Both arguments are stripped; an empty
    *media_type* is silently ignored (the CLI parser already validates).
    """
    mt = (media_type or "").strip()
    if not mt:
        return
    emb = (embedder or "").strip() if embedder else ""
    if not emb:
        _cli_solo_embedders.pop(mt, None)
        return
    _cli_solo_embedders[mt] = emb


def get_cli_solo_embedders() -> dict[str, str]:
    """Return a copy of the process-level solo-embedder CLI fallbacks."""
    return dict(_cli_solo_embedders)


def get_effective_solo_embedders() -> dict[str, str]:
    """Return the merged ``{media_type: embedder}`` dict for the current user.

    Combines the per-user :func:`get_solo_embedder_per_media_type` map
    (user explicit) with the process-level
    :data:`_cli_solo_embedders` (CLI fallback). User entries win per-key;
    missing user keys fall through to the CLI value. An **empty-string
    value** in the user map is a per-type opt-out sentinel - it removes
    that type from the merged map even if the CLI fallback has a
    value for it. This is the analog of setting ``solo_media_type=null``
    with ``solo_media_type_explicit=True`` to override
    ``--solo-media-type``.

    Validity (does the embedder still exist for this type?) is *not*
    checked here - the frontend resolves it against the live embedder
    registry on its end and falls back to the normal picker for any
    entry that no longer matches. Keeping validation client-side means a
    rename or removal never blocks the settings UI from rendering.
    """
    merged: dict[str, str] = {}
    for mt, emb in _cli_solo_embedders.items():
        if mt and isinstance(emb, str) and emb.strip():
            merged[mt] = emb.strip()
    user_map = get_solo_embedder_per_media_type()  # type: ignore[name-defined]  # autogen'd accessor
    if isinstance(user_map, dict):
        for mt, emb in user_map.items():
            if not isinstance(mt, str) or not mt:
                continue
            if isinstance(emb, str) and emb.strip():
                merged[mt] = emb.strip()
            else:
                # Empty-string sentinel - user explicitly opted out for
                # this type, so drop the CLI fallback too.
                merged.pop(mt, None)
    return merged


def get_effective_solo_embedder(media_type: str) -> str | None:
    """Return the effective solo embedder for *media_type*, or ``None``."""
    if not media_type:
        return None
    return get_effective_solo_embedders().get(media_type)


def apply_user_solo_embedder_per_media_type(value: dict[str, str] | None) -> None:
    """Replace the per-user ``solo_embedder_per_media_type`` map.

    Used by the settings PUT route. ``None`` clears every entry. Keys
    are stripped and skipped if empty. Values are stripped; an
    empty-string value is preserved as a **per-type opt-out sentinel**
    (overrides the CLI fallback for that type - see
    :func:`get_effective_solo_embedders`). The route layer is
    responsible for validating non-empty ``(media_type, embedder)``
    pairs against the live registries before calling this.
    """
    if value is None:
        set_solo_embedder_per_media_type({})  # type: ignore[name-defined]  # autogen'd accessor
        return
    cleaned: dict[str, str] = {}
    for mt, emb in value.items():
        if not isinstance(mt, str) or not mt.strip():
            continue
        if isinstance(emb, str) and emb.strip():
            cleaned[mt.strip()] = emb.strip()
        elif isinstance(emb, str):
            # Empty-string sentinel - preserve as opt-out marker.
            cleaned[mt.strip()] = ""
    set_solo_embedder_per_media_type(cleaned)  # type: ignore[name-defined]  # autogen'd accessor


def get_autorun_detectors() -> list[str]:
    """Return the current user's list of detector names flagged for autorun.

    Each name maps to a JSON file under ``data/detectors/``; scoring resolves
    the labelset's origins, re-embeds, trains an MLP, and applies it to the
    loaded dataset. Per-user (with a read-through to the server file for the
    built-in "default" user; see :func:`_read_value`).
    """
    raw = _read_value("autorun_detectors")
    return list(raw) if isinstance(raw, list) else []


def set_autorun_detectors(value: list[str]) -> None:
    """Set and persist the current user's full autorun detector list."""
    deduped = list(dict.fromkeys(value))  # dedupe, preserve order
    _write_value("autorun_detectors", deduped)


def add_autorun_detector(name: str) -> None:
    """Add a detector name to the current user's autorun list (idempotent).

    Atomic per-user read-modify-write: ``mutate_user`` re-reads the on-disk
    file under the cross-process lock, so a concurrent writer's entry is
    merged rather than clobbered. The ``seed`` captures the effective value
    (including the default-user read-through) for the first write, before the
    user has any entry of its own.
    """
    seed = get_autorun_detectors()

    def _add(cache: dict[str, Any]) -> None:
        base = cache["autorun_detectors"] if "autorun_detectors" in cache else seed
        cache["autorun_detectors"] = list(dict.fromkeys([*base, name]))

    mutate_user(_add)


def remove_autorun_detector(name: str) -> bool:
    """Remove a detector name from the current user's autorun list.

    Returns ``True`` if the name was present (pre-read). Atomic per-user RMW,
    same merge semantics as :func:`add_autorun_detector`.
    """
    seed = get_autorun_detectors()
    found = name in seed

    def _remove(cache: dict[str, Any]) -> None:
        base = cache["autorun_detectors"] if "autorun_detectors" in cache else seed
        cache["autorun_detectors"] = [n for n in base if n != name]

    mutate_user(_remove)
    return found


def is_autorun_detector(name: str) -> bool:
    """Check whether a detector name is in the autorun list."""
    return name in get_autorun_detectors()


# -------------------------------------------------------------------
# Plugin hiding (admin-side picker declutter)
# -------------------------------------------------------------------


def _normalize_hidden_plugins(value: Any) -> dict[str, set[str]]:
    """Coerce arbitrary input to ``{family: {name, ...}}`` form.

    Accepts ``dict[str, Iterable[str]]`` shapes and drops empty entries.
    Non-string keys / names and ``None`` values are silently skipped so a
    corrupt settings file doesn't crash plugin listings.
    """
    out: dict[str, set[str]] = {}
    if not isinstance(value, dict):
        return out
    for family, names in value.items():
        if not isinstance(family, str) or not family:
            continue
        if isinstance(names, (str, bytes)):
            continue
        try:
            members = {n for n in names if isinstance(n, str) and n}
        except TypeError:
            continue
        if members:
            out[family] = members
    return out


def set_cli_hidden_plugins(value: dict[str, Any] | None) -> None:
    """Replace the process-level ``--hide-plugin`` fallback in one shot.

    Called by ``app.py`` after parsing ``--hide-plugin family:name`` flags
    (or by tests that want to seed a known CLI hide list). ``None`` or an
    empty dict clears the fallback.
    """
    global _cli_hidden_plugins
    _cli_hidden_plugins = _normalize_hidden_plugins(value or {})


def add_cli_hidden_plugin(family: str, name: str) -> None:
    """Append ``(family, name)`` to the CLI hide list (idempotent).

    Used by the ``--hide-plugin`` argparse hook to accumulate one entry
    per flag occurrence.
    """
    if not family or not name:
        return
    _cli_hidden_plugins.setdefault(family, set()).add(name)


def get_cli_hidden_plugins() -> dict[str, set[str]]:
    """Return a defensive copy of the CLI-only hide map."""
    return {family: set(names) for family, names in _cli_hidden_plugins.items()}


def get_effective_hidden_plugins() -> dict[str, set[str]]:
    """Return the merged ``{family: {name, ...}}`` hide map.

    Combines the persisted ``hidden_plugins`` server setting with the
    process-level ``--hide-plugin`` fallback. The union semantics matter:
    a plugin is hidden if either source asks for it, so the CLI flag can
    only add hides (never un-hide something the settings file marks
    hidden).
    """
    persisted = _normalize_hidden_plugins(get_hidden_plugins())  # type: ignore[name-defined]
    merged: dict[str, set[str]] = {family: set(names) for family, names in persisted.items()}
    for family, names in _cli_hidden_plugins.items():
        merged.setdefault(family, set()).update(names)
    return merged


def is_plugin_hidden(family: str, name: str) -> bool:
    """Return True if *name* is hidden in *family* by the effective hide map.

    Static ``hidden_from_picker=True`` on a plugin class is **not**
    consulted here - that flag is already serialised on the plugin's
    ``to_dict()`` and filtered client-side. This function only answers
    "is the admin hiding this in this deployment?"
    """
    hidden = _cli_hidden_plugins.get(family)
    if hidden and name in hidden:
        return True
    persisted = get_hidden_plugins()  # type: ignore[name-defined]
    if not isinstance(persisted, dict):
        return False
    family_names = persisted.get(family)
    if not isinstance(family_names, (list, set, tuple)):
        return False
    return name in family_names


def filter_visible_plugins(family: str, plugins: Iterable[Any], *, id_attr: str = "name") -> list[Any]:
    """Drop plugins whose id-attribute is hidden in *family*.

    The single chokepoint for the listing routes. *id_attr* names the
    attribute that carries the plugin's registry id - ``"name"`` for the
    PluginBase families, ``"type_id"`` for :class:`MediaType` (whose
    registry key is the type id, not its human-readable name).
    """
    hidden = get_effective_hidden_plugins().get(family)
    if not hidden:
        return list(plugins)
    return [p for p in plugins if getattr(p, id_attr, None) not in hidden]


def filter_visible_plugin_dicts(
    family: str, plugin_dicts: Iterable[dict[str, Any]], *, id_key: str = "name"
) -> list[dict[str, Any]]:
    """Same as :func:`filter_visible_plugins` but for pre-serialised dicts.

    Reads ``dict[id_key]`` to compare against the hide set. Entries
    without that key are kept.
    """
    hidden = get_effective_hidden_plugins().get(family)
    if not hidden:
        return list(plugin_dicts)
    return [d for d in plugin_dicts if d.get(id_key) not in hidden]


# -------------------------------------------------------------------
# Directory path settings (server tier)
# -------------------------------------------------------------------


def _get_dir(key: str) -> Path:
    """Return a server-tier directory path setting as a :class:`~pathlib.Path`."""
    with _settings_lock:
        raw = _ensure_server_loaded().get(key, _server_defaults()[key])
    return Path(raw)


def _set_dir(key: str, value: str | Path) -> None:
    """Persist a server-tier directory path setting."""
    _ensure_server_loaded()
    coerced = str(value)
    _mutate_server_locked(lambda c: c.__setitem__(key, coerced))


def get_saved_datasets_dir() -> Path:
    """Return the configured saved-datasets directory."""
    return _get_dir("saved_datasets_dir")


def set_saved_datasets_dir(value: str | Path) -> None:
    """Set the saved-datasets directory."""
    _set_dir("saved_datasets_dir", value)


def get_detectors_dir() -> Path:
    """Return the configured detectors directory."""
    return _get_dir("detectors_dir")


def set_detectors_dir(value: str | Path) -> None:
    """Set the detectors directory."""
    _set_dir("detectors_dir", value)


def set_settings_path(path: str | Path) -> None:
    """Override the server-tier settings file path and reset its cache.

    Used by the CLI to point at a project- or run-specific settings file.
    Does not affect per-user settings files - those still live under
    :func:`vtsearch.auth.get_user_data_dir`.
    """
    global SETTINGS_PATH, _server_cache, _legacy_migrated
    with _settings_lock:
        SETTINGS_PATH = Path(path)
        _server_cache = None
        _legacy_migrated = False


def set_user_data_dir_override(path: Path | None) -> None:
    """Redirect per-user settings files under *path* (tests only).

    When *path* is set, every per-user settings file resolves to
    ``path / <username> / user_settings.json``, bypassing
    :func:`vtsearch.auth.get_user_data_dir`. Pass ``None`` to clear.
    """
    global _USER_DATA_DIR_OVERRIDE
    with _settings_lock:
        _USER_DATA_DIR_OVERRIDE = Path(path) if path is not None else None


def reset() -> None:
    """Reset every in-memory cache (for testing)."""
    global _server_cache, _legacy_migrated
    with _settings_lock:
        _server_cache = None
        _user_caches.clear()
        _sync_state.clear()
        _syncing.clear()
        _legacy_migrated = False
    with _user_sync_locks_guard:
        _user_sync_locks.clear()


# -------------------------------------------------------------------
# Settings source (bidirectional sync, per-user)
# -------------------------------------------------------------------


def get_settings_source_config() -> dict[str, Any] | None:
    """Return the active user's settings source config, or ``None`` if unset.

    Config shape::

        {
            "source_name": "server_json_file",
            "field_values": {"filepath": "data/{username}.settings.json"}
        }
    """
    from vtsearch.auth import get_current_user

    username = get_current_user()
    _ensure_user_loaded(username)
    with _settings_lock:
        cache = _user_caches.get(username, {})
        cfg = cache.get("settings_source")
    if isinstance(cfg, dict) and cfg.get("source_name"):
        return cfg
    return None


def set_settings_source_config(config: dict[str, Any] | None) -> None:
    """Set or clear the active user's settings source config."""
    from vtsearch.auth import get_current_user

    username = get_current_user()
    _ensure_user_loaded(username)

    def _apply(cache: dict[str, Any]) -> None:
        if config is None:
            cache.pop("settings_source", None)
        else:
            cache["settings_source"] = config

    sync_data = _mutate_user_locked(username, _apply)
    if config is None:
        # Source cleared - drop any cached sync state so a future
        # configure-then-read doesn't believe it's still "synced" to
        # the previously-configured target.
        with _settings_lock:
            _sync_state.pop(username, None)
        return
    if sync_data is not None:
        # ``_sync_to_source`` exports the full local dict to the new
        # source location and stamps the user as freshly synced
        # (so the next ``_ensure_user_loaded`` doesn't immediately
        # pull what we just pushed).
        _sync_to_source(username, sync_data)


# Map of setting key → setter function (generated dynamically).
_SETTER_MAP: dict[str, Any] | None = None


def _get_setter_map() -> dict:
    """Build a map of setting-key → setter-function by introspecting this module."""
    global _SETTER_MAP
    if _SETTER_MAP is not None:
        return _SETTER_MAP
    import vtsearch.settings as _self

    _SETTER_MAP = {}
    for attr_name in dir(_self):
        if attr_name.startswith("set_") and callable(getattr(_self, attr_name)):
            _SETTER_MAP[attr_name[4:]] = getattr(_self, attr_name)
    return _SETTER_MAP


def _apply_settings(imported: dict, skip_keys: set[str] | None = None) -> None:
    """Apply a dict of settings via this module's ``set_*`` functions.

    Unknown keys or values that fail validation are silently skipped.
    Keys in *skip_keys* are also skipped - used by the auto re-sync
    path so an upstream value doesn't silently overwrite a key the
    user has just edited locally.  Used by :func:`sync_from_settings_source`
    and by the settings-import route in ``routes/settings/io.py``.
    """
    setter_map = _get_setter_map()
    skip = skip_keys or set()
    for key, value in imported.items():
        if key in skip:
            continue
        setter = setter_map.get(key)
        if setter is not None:
            try:
                setter(value)
            except (TypeError, ValueError):
                pass  # Skip invalid values silently


def sync_from_settings_source() -> dict[str, Any] | None:
    """Pull settings from the active user's source and apply them.

    Returns the imported settings dict, or ``None`` if no source is
    configured or the source file doesn't exist yet.

    Triggered:

    - Automatically from :func:`_ensure_user_loaded` whenever the
      source's :meth:`SettingsSource.peek_version` token differs from
      the cached one (or no successful sync has happened yet this
      process lifetime).
    - Manually via ``POST /api/settings-sources/sync``.

    This (explicit) path **ignores the local ``dirty_keys`` set**: the
    user clicked "Sync now" precisely to get the source values, so a
    locally-edited key is overwritten and the dirty marker is cleared.
    """
    cfg = get_settings_source_config()
    if cfg is None:
        return None

    from vtsearch.auth import get_current_user
    from vtsearch.settings_io.sources import get_settings_source

    source = get_settings_source(cfg["source_name"])
    if source is None:
        logger.warning("Unknown settings source: %s", cfg["source_name"])
        return None

    field_values = cfg.get("field_values", {})
    new_version: Any = None
    try:
        new_version = source.peek_version(field_values)
    except Exception:
        new_version = None

    try:
        imported = source.load(field_values)
    except Exception as exc:
        logger.exception("Failed to load from settings source: %s", exc)
        return None

    if not imported:
        return None

    username = get_current_user()
    # The setters invoked by ``_apply_settings`` acquire ``_file_lock``
    # and then ``_settings_lock``. Holding ``_settings_lock`` here would
    # invert the canonical order - take the lock only to mutate
    # ``_syncing``, then drop it for the actual apply.
    with _settings_lock:
        _syncing.add(username)
    try:
        _apply_settings(imported)
    finally:
        with _settings_lock:
            _syncing.discard(username)

    with _settings_lock:
        _sync_state[username] = _UserSyncState(
            last_version=new_version,
            last_check_monotonic=time.monotonic(),
            last_sync_succeeded=True,
            dirty_keys=set(),
        )

    return imported


def _sync_to_source(username: str, data: dict[str, Any]) -> None:
    """Push *username*'s current settings to their active source (if any).

    Called from :func:`_write_value` / :func:`mutate_user` /
    :func:`set_settings_source_config` after the per-user file is
    written, **outside** the cross-process file lock so a slow sync
    target can't block other settings writes.  Strips the
    ``settings_source`` key itself to avoid circular config.

    On successful save the user is stamped as freshly synced
    (``last_version`` refreshed from the post-save ``peek_version``,
    ``dirty_keys`` cleared) - source now matches local, so the next
    :func:`_ensure_user_loaded` short-circuits via the fast path
    instead of pulling back the values we just pushed.
    """
    cfg = data.get("settings_source")
    if not isinstance(cfg, dict) or not cfg.get("source_name"):
        return

    from vtsearch.settings_io.sources import get_settings_source

    source = get_settings_source(cfg["source_name"])
    if source is None:
        return

    field_values = cfg.get("field_values", {})
    export_data = {k: v for k, v in data.items() if k not in _EXCLUDE_FROM_SOURCE_EXPORT}

    try:
        source.save(export_data, field_values)
    except Exception as exc:
        logger.exception("Failed to sync settings to source for %s: %s", username, exc)
        return

    # Source now matches local for every exported key - clear the dirty
    # set and refresh the version token so an auto re-sync doesn't fire
    # for the change we just exported.
    new_version: Any = None
    try:
        new_version = source.peek_version(field_values)
    except Exception:
        new_version = None
    with _settings_lock:
        _sync_state[username] = _UserSyncState(
            last_version=new_version,
            last_check_monotonic=time.monotonic(),
            last_sync_succeeded=True,
            dirty_keys=set(),
        )
