"""Decision-threshold computation for learned-sort scores.

GMM-, cross-calibration-, and safe-threshold helpers. These are media-
agnostic: they take score lists and label lists and return a single
float threshold. Detector-specific glue (sourcing ``X_list`` / ``y_list``
from votes, caching on ``DetectorContext``) lives in
:mod:`vtscore.detectors`.

The implementation is split across seven submodules, layered so that each one
only reads from those above it:

* :mod:`~vtscore.training.thresholds.knobs` - what an Inclusion value, a
  Train/Calibrate split and the sentinels *mean*.  Depends on nothing.
* :mod:`~vtscore.training.thresholds.costs` - what a cut *costs* on a labelled
  sample, under the weights the knob names.  Numpy only; the one definition the
  shipped Smart indicator and the eval harness both score through.
* :mod:`~vtscore.training.thresholds.gmm` - the 1-D two-component mixture, its
  anchored variant, and the rules that read a cut off a fit.  Self-contained.
* :mod:`~vtscore.training.thresholds.anchored` - the shipped path: per-fold
  anchored mixtures combined in quantile space, plus the voted-media haystack
  exclusion.
* :mod:`~vtscore.training.thresholds.conformal` - the rival estimator: fold
  splits and split-conformal quantiles over pooled held-out scores.
* :mod:`~vtscore.training.thresholds.blend` - the retired safe-threshold blend,
  kept as the anchored path's small-label fallback.
* :mod:`~vtscore.training.thresholds.precision_floor` - the precision-floor
  cut (#4224): the largest top-k whose estimated precision clears a floor, from
  the calibration folds' held-out votes, and :func:`reporting_line`, which
  decides whether a detector's line is the floor's or the Inclusion knob's.
  Reads :mod:`~vtscore.training.thresholds.gmm` for its sampling and
  sentinel filtering; otherwise numpy and scikit-learn.

Everything below is re-exported here, so ``vtscore.training.thresholds.X``
resolves exactly as it did when this was one module.  **Patch targets are the
exception**, because a stub has to be installed where the *caller* looks the
name up, and the split moved some of those lookups:

* A caller outside this package that imports lazily (``from
  vtscore.training.thresholds import fit_fold_anchored_cut`` inside a function,
  as :mod:`vtscore.detectors.training` does) re-reads the attribute off this
  package on every call, so patching the package still reaches it.
* A caller *inside* a submodule resolves its own module global, which this
  package's attribute is only a copy of.  Stubbing ``fit_gmm_threshold`` for
  :func:`~vtscore.training.thresholds.blend.calculate_safe_threshold`, or
  ``compute_fold_orderings`` for
  :func:`~vtscore.training.thresholds.conformal.calculate_cross_calibration_threshold`,
  means patching ``thresholds.blend`` / ``thresholds.conformal`` - not this
  package, where the rebind is silently ignored.
"""

from __future__ import annotations

from vtscore.training.thresholds.anchored import (
    EXCLUSION_MIN_REMAINDER,
    FOLD_ANCHOR_COMBINE,
    FOLD_ANCHOR_CUT_RULE,
    FOLD_ANCHOR_HINGE_RULES,
    FOLD_ANCHOR_QTILT_STEP,
    FOLD_ANCHOR_WEIGHT,
    FOLD_LEVEL_CUT_RULES,
    FoldAnchoredCut,
    apply_vote_exclusion,
    drop_voted,
    fit_fold_anchored_cut,
    fold_anchored_gmm_threshold,
    rank_transfer,
    resolve_exclusion_floor,
)
from vtscore.training.thresholds.blend import (
    _as_context,
    blend_gmm_threshold,
    calculate_safe_threshold,
    safe_blend_weight,
)
from vtscore.training.thresholds.conformal import (
    _DITHER_SAMPLE_ROWS,
    CALIBRATION_SPLIT_SEED,
    CONFORMAL_BASE_BUDGET,
    CONFORMAL_QPOS_MAX,
    FOLD_CONFORMAL_COMBINES,
    CalibrationFolds,
    _calibration_cache_key,
    _compute_fold_orderings_grouped,
    _dithered_count,
    _fold_fit_ordering,
    _group_node_blocks,
    _grouped_folds,
    _per_bag_fit_weights,
    _pooled_group_scores,
    _row_wise_fold_ordering,
    _score_rows_digest,
    _split_dither_rng,
    _torch_fold_ordering,
    calculate_cross_calibration_threshold,
    calibration_folds,
    calibration_folds_cached,
    combined_fold_conformal_threshold,
    compute_fold_orderings,
    compute_grouped_fold_node_scores,
    conformal_threshold,
    per_fold_conformal_cuts,
    threshold_from_fold_orderings,
    threshold_from_folds,
)
from vtscore.training.thresholds.gmm import (
    _ANCHOR_MIN_WEIGHT,
    _ANCHOR_VAR_FLOOR_FRAC,
    _ANCHORED_EM_LOGLIK_TOL,
    _ANCHORED_EM_MAX_ITER,
    _ANCHORED_EM_TOL,
    _GMM_MAX_SAMPLES,
    ANCHOR_WEIGHT_DEFAULT,
    CUT_KIND_CONTINUED,
    CUT_KIND_DEGENERATE_MIDPOINT,
    CUT_KIND_INTERIOR,
    GmmFit1D,
    _anchor_loglik_terms,
    _anchored_em,
    _quadratic_roots,
    _record_stopping,
    _rate_cut,
    _weighted_gaussian_crossing,
    anchored_gmm_fit,
    TEXT_SORT_CUT_RULE,
    TEXT_SORT_CUT_RULES,
    TEXT_SORT_SEPARATION_D,
    TEXT_SORT_TAIL_K,
    ashman_d,
    bulk_location_scale,
    calculate_gmm_threshold,
    converge_score_gmm,
    resolve_text_sort_cut_rule,
    guarded_text_sort_threshold,
    text_sort_threshold,
    fit_anchored_score_gmm,
    fit_gmm_threshold,
    _EM_LOGLIK_TOL,
    _EM_MAX_ITER,
    _EM_TOL,
    _TEXT_SORT_CONVERGED_MAX_ITER,
    _TEXT_SORT_CONVERGED_TOL,
    _KMEANS_MAX_ITER,
    _NO_ANCHORS,
    _plain_em,
    _two_means_init,
    fit_score_gmm,
    fit_score_gmm_sklearn,
    gmm_cut_from_fit,
    gmm_fit_array,
    scored_ordering,
    snap_cut_to_sample,
)
from vtscore.training.thresholds.costs import weighted_error_cost

# The floor an unset setting resolves to lives in the config layer, so settings
# can read it without importing the training stack; it is re-exported here
# beside the estimator it parameterises.
from vtscore.config.runtime import DEFAULT_MIN_PRECISION
from vtscore.training.thresholds.spot_check import (
    CHECK_ALPHA,
    CHECK_BASE_CANDIDATE,
    CHECK_CANCELLED,
    CHECK_MIN_PICKS,
    CHECK_PROVENANCE,
    CHECK_RUNNING,
    FLOOR_CONFIRMED,
    FLOOR_SHORT,
    FLOOR_STATES,
    FLOOR_UNCHECKED,
    CheckSchedule,
    FloorState,
    LikelyRange,
    LineRanking,
    SpotCheck,
    applicable_result,
    check_schedule,
    clopper_pearson_lower,
    clopper_pearson_upper,
    floor_count,
    floor_line,
    floor_state,
    likely_range,
    line_under,
    range_tail,
    rounds_for,
    BAND_BASE,
    WALK_DEEPER,
    WALK_SHALLOWER,
    WALK_START,
    band_edges,
    bands_for,
    MIXTURE_MIN_STD_SHARE,
    acquisition_count,
    acquisition_threshold,
    mixture_count,
    mixture_positives,
    mixture_posterior,
    walk_positives,
    fbeta_count,
    fbeta_score,
    balance_schedule,
    check_shape,
    balance_count,
    balance_line,
    aim_words,
    band_edges_fine,
    balance_state,
    gate_balance_state,
    resolve_line_knobs,
    applicable_balance,
    BalanceState,
    BALANCE_CHECKED,
    BALANCE_GATE,
    BALANCE_PRESETS,
    CHECK_ADVISORY,
    CHECK_SHAPES,
    CHECK_TRIM,
    BALANCE_STATES,
    BETA_MAX,
    BETA_MIN,
    DEFAULT_BETA,
)
from vtscore.training.thresholds.line_test import (
    ABOVE,
    BELOW,
    DEFAULT_BUDGETS,
    FOUND_WORDS,
    JEFFREYS,
    MODEL_FLOOR,
    PHASE_DONE,
    PHASE_MATCHES,
    PHASE_MISSES,
    PHASE_NOTHING,
    PHASE_SCORE,
    PHASES,
    SIDES,
    STOP_BUDGET,
    STOP_DRY_RUN,
    STOP_EXHAUSTED,
    STOP_REASONS,
    STOP_WIDTH,
    TEST_ALPHA,
    TEST_DRAW_SEED,
    TEST_DRAWS,
    TEST_PROVENANCE,
    Band,
    EdgeEstimate,
    Estimate,
    LineTest,
    PhaseReport,
    LineBudgets,
    LineEstimates,
    found_words,
    line_bands,
    line_phase,
)
from vtscore.training.thresholds.precision_floor import (
    MIN_BOOTSTRAP_FITS,
    MIN_CALIBRATION_POSITIVES,
    NO_PRECISION_FLOOR,
    PRECISION_BOOTSTRAP_REFITS,
    PRECISION_BOOTSTRAP_SEED,
    PRECISION_COORDINATES,
    PRECISION_FITS,
    PRECISION_FLOOR_FALLBACK_INCLUSION,
    PRECISION_LOWER_PERCENTILE,
    PrecisionFloorCurve,
    PrecisionFloorCut,
    PrecisionFloorEstimate,
    PrecisionFloorStatus,
    ReportingLine,
    eligible_fold_orderings,
    em_prior_shift,
    fit_posterior,
    fit_precision_floor_curve,
    fold_rank_evidence,
    line_inclusion,
    percentile_in,
    precision_floor_cut,
    precision_lower_bound_curve,
    reporting_line,
    resolve_min_precision,
    unpromised,
)
from vtscore.training.thresholds.labels_line import (
    ClassScoreModel,
    LabelsLine,
    class_score_model,
    CorpusNegatives,
    corpus_cut,
    corpus_fit,
    corpus_posteriors,
    corpus_prevalence,
    corpus_sigma_floor,
    RELATIVE_SIGMA_FLOOR,
    WEAK_CHECK_COOLDOWN,
    WEAK_CHECK_MIN_VOTES,
    WEAK_SEPARATION_D,
    estimate_positives,
    fit_labels_line,
    labels_line_threshold,
    weak_check_due,
)
from vtscore.training.thresholds.knobs import (
    ACQUISITION_ARGMAX_FACTOR,
    ACQUISITION_INCLUSION_OFFSET,
    INCLUSION_MAX,
    INCLUSION_MIN,
    INCLUSION_SEARCH_SPAN,
    NO_GOOD_THRESHOLD,
    PRODUCTION_SPLIT,
    PRODUCTION_SPLIT_BY_SPACE,
    acquisition_inclusion,
    classify_threshold_provenance,
    inclusion_cost_weights,
    production_split_for,
)

__all__ = [
    "ABOVE",
    "BELOW",
    "DEFAULT_BUDGETS",
    "FOUND_WORDS",
    "JEFFREYS",
    "MODEL_FLOOR",
    "PHASE_DONE",
    "PHASE_MATCHES",
    "PHASE_MISSES",
    "PHASE_NOTHING",
    "PHASE_SCORE",
    "PHASES",
    "SIDES",
    "STOP_BUDGET",
    "STOP_DRY_RUN",
    "STOP_EXHAUSTED",
    "STOP_REASONS",
    "STOP_WIDTH",
    "TEST_ALPHA",
    "TEST_DRAW_SEED",
    "TEST_DRAWS",
    "TEST_PROVENANCE",
    "Band",
    "EdgeEstimate",
    "Estimate",
    "LineTest",
    "PhaseReport",
    "LineBudgets",
    "LineEstimates",
    "found_words",
    "line_bands",
    "line_phase",
    "ClassScoreModel",
    "LabelsLine",
    "class_score_model",
    "CorpusNegatives",
    "corpus_cut",
    "corpus_fit",
    "corpus_posteriors",
    "corpus_prevalence",
    "corpus_sigma_floor",
    "RELATIVE_SIGMA_FLOOR",
    "WEAK_CHECK_COOLDOWN",
    "WEAK_CHECK_MIN_VOTES",
    "WEAK_SEPARATION_D",
    "estimate_positives",
    "fit_labels_line",
    "labels_line_threshold",
    "weak_check_due",
    "ACQUISITION_ARGMAX_FACTOR",
    "ACQUISITION_INCLUSION_OFFSET",
    "INCLUSION_MAX",
    "INCLUSION_MIN",
    "INCLUSION_SEARCH_SPAN",
    "NO_GOOD_THRESHOLD",
    "PRODUCTION_SPLIT",
    "PRODUCTION_SPLIT_BY_SPACE",
    "acquisition_inclusion",
    "classify_threshold_provenance",
    "inclusion_cost_weights",
    "production_split_for",
    "weighted_error_cost",
    "DEFAULT_MIN_PRECISION",
    "BAND_BASE",
    "WALK_DEEPER",
    "WALK_SHALLOWER",
    "WALK_START",
    "band_edges",
    "bands_for",
    "MIXTURE_MIN_STD_SHARE",
    "acquisition_count",
    "acquisition_threshold",
    "mixture_count",
    "mixture_positives",
    "mixture_posterior",
    "walk_positives",
    "fbeta_count",
    "fbeta_score",
    "balance_schedule",
    "check_shape",
    "balance_count",
    "balance_line",
    "aim_words",
    "band_edges_fine",
    "balance_state",
    "gate_balance_state",
    "resolve_line_knobs",
    "applicable_balance",
    "BalanceState",
    "BALANCE_CHECKED",
    "BALANCE_GATE",
    "BALANCE_PRESETS",
    "CHECK_ADVISORY",
    "CHECK_SHAPES",
    "CHECK_TRIM",
    "BALANCE_STATES",
    "BETA_MAX",
    "BETA_MIN",
    "DEFAULT_BETA",
    "CHECK_ALPHA",
    "CHECK_BASE_CANDIDATE",
    "CHECK_CANCELLED",
    "CHECK_MIN_PICKS",
    "CHECK_PROVENANCE",
    "CHECK_RUNNING",
    "FLOOR_CONFIRMED",
    "FLOOR_SHORT",
    "FLOOR_STATES",
    "FLOOR_UNCHECKED",
    "CheckSchedule",
    "FloorState",
    "LikelyRange",
    "LineRanking",
    "SpotCheck",
    "applicable_result",
    "check_schedule",
    "clopper_pearson_lower",
    "clopper_pearson_upper",
    "floor_count",
    "floor_line",
    "floor_state",
    "likely_range",
    "line_under",
    "range_tail",
    "rounds_for",
    "MIN_BOOTSTRAP_FITS",
    "MIN_CALIBRATION_POSITIVES",
    "NO_PRECISION_FLOOR",
    "PRECISION_BOOTSTRAP_REFITS",
    "PRECISION_BOOTSTRAP_SEED",
    "PRECISION_COORDINATES",
    "PRECISION_FITS",
    "PRECISION_FLOOR_FALLBACK_INCLUSION",
    "PRECISION_LOWER_PERCENTILE",
    "PrecisionFloorCurve",
    "PrecisionFloorCut",
    "PrecisionFloorEstimate",
    "PrecisionFloorStatus",
    "ReportingLine",
    "eligible_fold_orderings",
    "em_prior_shift",
    "fit_posterior",
    "fit_precision_floor_curve",
    "fold_rank_evidence",
    "line_inclusion",
    "percentile_in",
    "precision_floor_cut",
    "precision_lower_bound_curve",
    "reporting_line",
    "resolve_min_precision",
    "unpromised",
    "ANCHOR_WEIGHT_DEFAULT",
    "CUT_KIND_CONTINUED",
    "CUT_KIND_DEGENERATE_MIDPOINT",
    "CUT_KIND_INTERIOR",
    "GmmFit1D",
    "_ANCHOR_MIN_WEIGHT",
    "_ANCHOR_VAR_FLOOR_FRAC",
    "_ANCHORED_EM_LOGLIK_TOL",
    "_ANCHORED_EM_MAX_ITER",
    "_ANCHORED_EM_TOL",
    "_GMM_MAX_SAMPLES",
    "_anchor_loglik_terms",
    "_anchored_em",
    "_quadratic_roots",
    "_record_stopping",
    "_rate_cut",
    "_weighted_gaussian_crossing",
    "anchored_gmm_fit",
    "TEXT_SORT_CUT_RULE",
    "TEXT_SORT_CUT_RULES",
    "TEXT_SORT_SEPARATION_D",
    "TEXT_SORT_TAIL_K",
    "ashman_d",
    "bulk_location_scale",
    "calculate_gmm_threshold",
    "converge_score_gmm",
    "resolve_text_sort_cut_rule",
    "guarded_text_sort_threshold",
    "text_sort_threshold",
    "fit_anchored_score_gmm",
    "fit_gmm_threshold",
    "_EM_LOGLIK_TOL",
    "_EM_MAX_ITER",
    "_EM_TOL",
    "_TEXT_SORT_CONVERGED_MAX_ITER",
    "_TEXT_SORT_CONVERGED_TOL",
    "_KMEANS_MAX_ITER",
    "_NO_ANCHORS",
    "_plain_em",
    "_two_means_init",
    "fit_score_gmm",
    "fit_score_gmm_sklearn",
    "gmm_cut_from_fit",
    "gmm_fit_array",
    "scored_ordering",
    "snap_cut_to_sample",
    "EXCLUSION_MIN_REMAINDER",
    "FOLD_ANCHOR_COMBINE",
    "FOLD_ANCHOR_CUT_RULE",
    "FOLD_ANCHOR_HINGE_RULES",
    "FOLD_ANCHOR_QTILT_STEP",
    "FOLD_ANCHOR_WEIGHT",
    "FOLD_LEVEL_CUT_RULES",
    "FoldAnchoredCut",
    "apply_vote_exclusion",
    "drop_voted",
    "fit_fold_anchored_cut",
    "fold_anchored_gmm_threshold",
    "rank_transfer",
    "resolve_exclusion_floor",
    "CALIBRATION_SPLIT_SEED",
    "CONFORMAL_BASE_BUDGET",
    "CONFORMAL_QPOS_MAX",
    "CalibrationFolds",
    "FOLD_CONFORMAL_COMBINES",
    "_DITHER_SAMPLE_ROWS",
    "_calibration_cache_key",
    "_compute_fold_orderings_grouped",
    "_dithered_count",
    "_fold_fit_ordering",
    "_group_node_blocks",
    "_grouped_folds",
    "_per_bag_fit_weights",
    "_pooled_group_scores",
    "_row_wise_fold_ordering",
    "_score_rows_digest",
    "_split_dither_rng",
    "_torch_fold_ordering",
    "calculate_cross_calibration_threshold",
    "calibration_folds",
    "calibration_folds_cached",
    "combined_fold_conformal_threshold",
    "compute_fold_orderings",
    "compute_grouped_fold_node_scores",
    "conformal_threshold",
    "per_fold_conformal_cuts",
    "threshold_from_fold_orderings",
    "threshold_from_folds",
    "_as_context",
    "blend_gmm_threshold",
    "calculate_safe_threshold",
    "safe_blend_weight",
]
