#!/usr/bin/env node
/**
 * Stamp the frontend bundle with the commit it was built from.
 *
 * `vtsearch.__version__` is the UTC timestamp of HEAD's commit, so the *server*
 * always reports exactly which code it is running. The bundle under `static/`
 * had no such stamp, and `static/` is a gitignored build artifact — so pulling
 * new code and restarting `python app.py` without rebuilding the frontend
 * leaves a new server serving an old SPA, with nothing anywhere saying so.
 *
 * That is not hypothetical: issue #2898 burned three round-trips on an exporter
 * feature that worked server-side and worked in the current bundle, because the
 * reporter's browser was running a bundle from before the feature existed and
 * the Settings dialog's "v <version>" line — the *server's* version — looked
 * perfectly up to date.
 *
 * This writes `src/app/generated/build-stamp.ts` (gitignored, alongside the
 * generated API client) with the same value the Python package computes, so the
 * running app can compare the two and say something when they disagree.
 *
 * Resolution order matches `vtsearch/__init__.py`:
 *   1. `VTSEARCH_VERSION` env — what the Dockerfile passes when `.git` is absent
 *   2. git: `git log -1 --format=%ct HEAD`, formatted as ISO-8601 Z
 *   3. `0.0.0-unknown`
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const FALLBACK = '0.0.0-unknown';
const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(frontendRoot, 'src', 'app', 'generated', 'build-stamp.ts');

/** Format a unix timestamp the way `vtsearch._format_iso_utc` does. */
function formatIsoUtc(unixSeconds) {
  return new Date(unixSeconds * 1000).toISOString().replace(/\.\d{3}Z$/, 'Z');
}

function fromGit() {
  const res = spawnSync('git', ['-C', resolve(frontendRoot, '..'), 'log', '-1', '--format=%ct', 'HEAD'], {
    encoding: 'utf8',
    timeout: 5000,
  });
  const ts = (res.stdout || '').trim();
  return res.status === 0 && /^\d+$/.test(ts) ? formatIsoUtc(Number(ts)) : null;
}

const version = process.env.VTSEARCH_VERSION?.trim() || fromGit() || FALLBACK;

const contents = `// GENERATED by frontend/scripts/build-stamp.mjs — do not edit, do not commit.
// The commit this bundle was built from; compared against GET /api/version at
// runtime so a stale \`static/\` build cannot masquerade as a fresh one (#2898).
export const BUILD_STAMP = ${JSON.stringify(version)};
`;

mkdirSync(dirname(outPath), { recursive: true });
// Only rewrite when the value moved: an unchanged file keeps the Angular
// dev-server's file watcher from rebuilding on every `npm start`.
let existing = null;
try {
  existing = readFileSync(outPath, 'utf8');
} catch {
  /* first run */
}
if (existing !== contents) {
  writeFileSync(outPath, contents, 'utf8');
  console.log(`[build-stamp] ${version}`);
}
