"""Render a GitHub-style 7x24 punch card of PR merge times.

PR merges are a cleaner "when did Sam actually touch this" signal than commits,
because Claude commits run unattended in the cloud - only the merge-button press
reflects a human at the keyboard.

Reproducing the data file (scripts/punchcard/pr_merges.txt):
    Each line is "<pr_number>|<merged_at_utc_iso8601>". Generated by
    paginating the GitHub Search API (is:merged, capped at 1000 results) and
    backfilling older PRs with the REST list endpoint (sort=created asc),
    then jq-extracting (.number, .merged_at) and sorting unique by PR number.

Output: scripts/punchcard/vtsearch_pr_punchcard.png
"""

from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import matplotlib.pyplot as plt
import numpy as np

LOCAL_TZ = ZoneInfo("America/New_York")
WEEKDAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
HERE = Path(__file__).resolve().parent
DATA_PATH = HERE / "pr_merges.txt"
OUT_PATH = HERE / "vtsearch_pr_punchcard.png"

counts = np.zeros((7, 24), dtype=int)
dates = []
for line in DATA_PATH.read_text().splitlines():
    line = line.strip()
    if not line:
        continue
    _, ts = line.split("|", 1)
    dt = datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(LOCAL_TZ)
    counts[dt.weekday(), dt.hour] += 1
    dates.append(dt.date())

total = int(counts.sum())
max_count = int(counts.max())
date_min = min(dates).isoformat()
date_max = max(dates).isoformat()

fig, ax = plt.subplots(figsize=(14, 4.5))
fig.patch.set_facecolor("white")

xs, ys, sizes = [], [], []
for d in range(7):
    for h in range(24):
        c = counts[d, h]
        if c == 0:
            continue
        xs.append(h)
        ys.append(d)
        sizes.append(c / max_count * 600 + 10)

ax.scatter(xs, ys, s=sizes, color="#238636", alpha=0.85, edgecolors="white", linewidths=0.5)

ax.set_xticks(range(24))
ax.set_xticklabels([f"{h:02d}" for h in range(24)], fontsize=9)
ax.set_yticks(range(7))
ax.set_yticklabels(WEEKDAY_LABELS, fontsize=10)
ax.set_ylim(-0.6, 6.6)
ax.set_xlim(-0.6, 23.6)
ax.invert_yaxis()
ax.set_xlabel("Hour of day (America/New_York)", fontsize=10)
ax.grid(True, linestyle=":", alpha=0.35)
ax.set_axisbelow(True)
for spine in ("top", "right"):
    ax.spines[spine].set_visible(False)

ax.set_title(
    f"VTSearch PR merges - {total} merged PRs, {date_min} to {date_max}",
    fontsize=12,
    loc="left",
    pad=12,
)

legend_counts = sorted({1, max(1, max_count // 4), max(1, max_count // 2), max_count})
legend_handles = [
    plt.scatter([], [], s=c / max_count * 600 + 10, color="#238636", alpha=0.85, edgecolors="white")
    for c in legend_counts
]
ax.legend(
    legend_handles,
    [f"{c} merges" for c in legend_counts],
    loc="upper left",
    bbox_to_anchor=(1.01, 1.0),
    frameon=False,
    fontsize=9,
    labelspacing=1.2,
    borderpad=0.8,
)

plt.tight_layout()
plt.savefig(OUT_PATH, dpi=160, bbox_inches="tight", facecolor="white")
print(f"Saved {OUT_PATH}  total={total}  max_bucket={max_count}  range={date_min}..{date_max}")
