#!/usr/bin/env bash
# Install guard-shared-checkout.sh into the hooks dir of each VTSearch git dir on
# the GRID, so a commit in the shared checkout or the deploy clone is refused.
#
#   bash scripts/grid/install-guard-hook.sh [<checkout> ...]
#
# Default checkouts: /exp/$USER/projects/VTSearch (whose .git every worktree
# shares, so one install covers all of them) and /expscratch/$USER/projects/VTSearch
# (the deploy clone, a separate clone with its own .git).
#
# What it writes, into <git-common-dir>/hooks/:
#   guard-shared-checkout.sh  a copy of the tracked script (re-run this to refresh it)
#   pre-commit.legacy         when pre-commit owns pre-commit: its hook runs
#                             <type>.legacy first and ORs the exit code in, and a
#                             later `pre-commit install` leaves it alone
#   pre-commit                when nothing owns it yet (a later `pre-commit install`
#                             moves it to pre-commit.legacy itself)
#   pre-merge-commit          same guard for a merge that makes a commit
# It refuses to overwrite a hook it did not write. Idempotent.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/guard-shared-checkout.sh"
marker="# vtsearch-guard-shared-checkout (scripts/grid/install-guard-hook.sh)"

if [[ $# -eq 0 ]]; then
    set -- "/exp/$USER/projects/VTSearch" "/expscratch/$USER/projects/VTSearch"
fi

stub() {
    printf '#!/usr/bin/env bash\n%s\nexec bash "$(dirname "$0")/guard-shared-checkout.sh"\n' "$marker"
}

write_hook() {  # <path>
    local path="$1"
    if [[ -e "$path" ]] && ! grep -qF "$marker" "$path"; then
        echo "  SKIP $path: exists and was not written by this installer" >&2
        return 1
    fi
    stub >"$path"
    chmod +x "$path"
    echo "  wrote $path"
}

rc=0
for co in "$@"; do
    [[ -d "$co" ]] || { echo "skip $co: no such dir"; continue; }
    common="$(git -C "$co" rev-parse --path-format=absolute --git-common-dir)"
    hooks="$(git -C "$co" rev-parse --path-format=absolute --git-path hooks)"
    echo "$co (git dir $common)"
    mkdir -p "$hooks"
    install -m 0755 "$src" "$hooks/guard-shared-checkout.sh"
    echo "  wrote $hooks/guard-shared-checkout.sh"
    if [[ -f "$hooks/pre-commit" ]] && grep -q "File generated by pre-commit" "$hooks/pre-commit"; then
        write_hook "$hooks/pre-commit.legacy" || rc=1
    else
        write_hook "$hooks/pre-commit" || rc=1
    fi
    write_hook "$hooks/pre-merge-commit" || rc=1
done
exit $rc
