"""Check that the vtscore package docs still cover the vtscore package tree.

Two invariants, both cheap (no imports, no parsing beyond a regex sweep):

1. **Every top-level module and sub-package of ``vtscore/`` is documented.**
   Each maps to exactly one file under ``vtscore/docs/packages/`` via
   :data:`DOC_FOR`, and that file must mention it. This is what stops a new
   subpackage from shipping with no doc at all — the failure mode that left
   ``projection``, ``timing``, ``io``, ``gpu_backends``, ``single_instance``
   and ``datasource_importers`` undocumented (issue #2999).

2. **No ``file.py:NNN`` line anchors anywhere in ``vtscore/docs/``.** Every
   such anchor in the doc set had rotted, most by hundreds of lines, because
   nothing ties a code edit to the prose that cites it. The policy is to
   reference module-and-symbol instead: stable, greppable, and correct after
   any edit that doesn't move the symbol.

What this deliberately does *not* check: that the prose is accurate, or that
every function is described. Those need a reader. This checks the mechanical
half — the half that rots silently.

Run from the repo root:
    python scripts/check-vtscore-docs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "vtscore"
DOCS = PKG / "docs" / "packages"

#: Which doc covers which top-level entry of ``vtscore/``. Keys are the entry
#: names as they appear on disk (a directory name, or a ``.py`` filename);
#: values are the doc basename under ``vtscore/docs/packages/``. Several
#: entries may share one doc — the CLI modules and the top-level runtime
#: modules are each documented as a group.
DOC_FOR: dict[str, str] = {
    "cli.py": "cli.md",
    "cli_pipeline.py": "cli.md",
    "cli_progress.py": "cli.md",
    "concurrency": "concurrency.md",
    "config.py": "config.md",
    "converters": "converters.md",
    "datasets": "datasets.md",
    "datasource_importers": "datasource-importers.md",
    "detectors": "detectors.md",
    "embedding": "embedding.md",
    "eval": "eval.md",
    "exporters": "exporters.md",
    "gpu_backends.py": "runtime-modules.md",
    "io.py": "runtime-modules.md",
    "labels": "labels.md",
    "media": "media.md",
    "plugins": "plugins.md",
    "projection": "projection.md",
    "security": "security.md",
    "seed_importers": "seed-importers.md",
    "single_instance.py": "runtime-modules.md",
    "state": "state.md",
    "sync": "sync.md",
    "timing": "timing.md",
    "training": "training.md",
    "utils": "utils.md",
}

#: Entries that are intentionally undocumented, with the reason. A hook seam
#: with a no-op default carries its whole contract in its docstring; the docs
#: directory documents itself.
EXEMPT: dict[str, str] = {
    "__init__.py": "package init: version resolution only",
    "_version.txt": "generated by the Docker build, gitignored",
    "achievements_hooks.py": "hook seam, library default is a no-op",
    "docs": "the documentation itself",
}

LINE_ANCHOR = re.compile(r"\.py:\d+")


def _top_level_entries() -> list[str]:
    """Names of every top-level module / sub-package under ``vtscore/``."""
    out = []
    for entry in sorted(PKG.iterdir()):
        if entry.name.startswith(".") or entry.name == "__pycache__":
            continue
        if entry.is_dir() or entry.suffix == ".py" or entry.name == "_version.txt":
            out.append(entry.name)
    return out


def _check_coverage() -> list[str]:
    errors: list[str] = []
    for name in _top_level_entries():
        if name in EXEMPT:
            continue
        doc_name = DOC_FOR.get(name)
        if doc_name is None:
            errors.append(
                f"vtscore/{name} has no entry in DOC_FOR: write a packages/ doc for it "
                f"(or add it to EXEMPT with a reason), then map it here."
            )
            continue
        doc = DOCS / doc_name
        if not doc.exists():
            errors.append(f"vtscore/{name} maps to packages/{doc_name}, which does not exist.")
            continue
        # A doc "covers" an entry when it names its path at least once. The
        # module tables do this by construction.
        needle = f"vtscore/{name}"
        if needle not in doc.read_text():
            errors.append(
                f"packages/{doc_name} never mentions `{needle}` — it is supposed to document it. "
                f"Add it to that doc's Contents table."
            )
    return errors


def _check_line_anchors() -> list[str]:
    errors: list[str] = []
    for doc in sorted((PKG / "docs").rglob("*.md")):
        for lineno, line in enumerate(doc.read_text().splitlines(), 1):
            if LINE_ANCHOR.search(line):
                rel = doc.relative_to(ROOT)
                errors.append(
                    f"{rel}:{lineno}: line-number anchor ({LINE_ANCHOR.search(line).group()}). "
                    f"Cite the module and symbol instead — line numbers rot on the next edit."
                )
    return errors


def main() -> int:
    errors = _check_coverage() + _check_line_anchors()
    if errors:
        print("vtscore docs check failed:\n", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1
    print(f"vtscore docs OK ({len(_top_level_entries()) - len(EXEMPT)} entries covered).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
