#!/usr/bin/env python3
"""Generate registry inventories embedded in the documentation.

Hand-maintained copies of registry contents (embedders, plugin families,
demo datasets, converters, ...) were the single most repeated documentation
defect: roughly ten documents re-tabulated the same registries by hand and
disagreed with the code and with each other.  This script makes those tables
*generated*: a doc marks a region with

    <!-- BEGIN GENERATED: <region-id> -->
    ...                                          (content owned by this script)
    <!-- END GENERATED: <region-id> -->

and this script rewrites everything between the markers from the live
registries (``vtscore.plugins.inventory``, ``vtscore.media``, the demo-dataset
declarations on each media type).  A generated table cannot be fixed *wrong*,
and a new plugin/demo/family shows up in the docs by re-running the generator
instead of by remembering ten call sites.

Usage:
    python scripts/gen-docs-inventories.py            # rewrite regions in place
    python scripts/gen-docs-inventories.py --check    # exit 1 if anything is stale

``--check`` runs as part of ``./run-tests.sh`` (same shape as the OpenAPI
snapshot gate): regenerate, diff against the committed docs, fail with the
regeneration command on mismatch.

Region ids
----------
Fixed ids: ``embedders``, ``embedder-files``, ``embedder-dims``,
``media-types``, ``plugin-families``, ``lessons-index`` (the last one indexes
``scripts/experiments/lessons/`` off the filesystem rather than a registry).
Parameterised ids:
``plugins:<family>`` (roster of one plugin family, e.g.
``plugins:converters``) and ``demos:<type_id>`` (demo-dataset table of one
media type, e.g. ``demos:audio``).  An unknown id is a hard error, and every
media type that declares demo datasets must have its ``demos:<type_id>``
region somewhere in the scanned docs, so new media types cannot ship
undocumented demos.

Every tracked ``*.md`` file is scanned, so a doc can adopt a region without
touching this script.
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

REGION_RE = re.compile(
    r"(<!-- BEGIN GENERATED: (?P<id>[a-z0-9_:-]+) -->\n)(?P<body>.*?)(<!-- END GENERATED: (?P=id) -->)",
    re.DOTALL,
)
ANY_MARKER_RE = re.compile(r"<!-- (?:BEGIN|END) GENERATED: [a-z0-9_:-]+ -->")

NOTE = (
    "<!-- Generated by scripts/gen-docs-inventories.py; do not edit by hand. "
    "Refresh with: python scripts/gen-docs-inventories.py -->"
)

REGEN_HINT = "Run 'python scripts/gen-docs-inventories.py' and commit the result."


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Registry access (imported lazily so --help stays instant)
# ---------------------------------------------------------------------------


def _inventory() -> dict:
    """Full plugin inventory: library families plus the app-tier settings families."""
    from vtsearch.shim import register_app_plugin_families
    from vtscore.plugins.inventory import gather_plugins

    register_app_plugin_families()
    return gather_plugins()


def _sorted_embedders() -> list:
    from vtscore.media import all_embedders

    return sorted(all_embedders(), key=lambda e: (e.media_type_id, not e.is_default, e.name))


def _media_types() -> list:
    from vtscore.media import all_types

    return sorted(all_types(), key=lambda t: t.type_id)


# ---------------------------------------------------------------------------
# Region builders
# ---------------------------------------------------------------------------


def build_embedders() -> str:
    """Full embedder roster: identity, model, dimension, capability notes."""
    rows = []
    for e in _sorted_embedders():
        notes = []
        if e.is_default:
            notes.append("**default** for its media type")
        if e.eval_only:
            notes.append("**evaluation only** — registered, but withheld from the app's pickers")
        if not e.supports_text:
            notes.append("no text queries")
        if e.supports_patch_regions:
            notes.append("patch grid (region-aware)")
        if e.supports_geometric_verification:
            notes.append("geometric verification")
        if e.license_notice:
            notes.append("restricted model license")
        rows.append(
            [
                f"`{e.media_type_id}`",
                f"`{e.name}`",
                e.display_name,
                f"`{e.model_id}`" if e.model_id else "—",
                str(e.embedding_dim) if e.embedding_dim else "—",
                "; ".join(notes) or "—",
            ]
        )
    return _table(["Media type", "Embedder", "Display name", "Model", "Dim", "Notes"], rows)


def build_embedder_files() -> str:
    """File/class map of every registered embedder (for the extending guide)."""
    rows = []
    for e in _sorted_embedders():
        module = type(e).__module__
        path = module.replace(".", "/") + ".py"
        rows.append(
            [
                f"`{path.removeprefix('vtscore/media/')}`",
                f"`{type(e).__name__}`",
                f"`{e.name}`",
                f"`{e.media_type_id}`",
                "✅" if e.is_default else "",
            ]
        )
    return _table(["File (under `vtscore/media/`)", "Class", "Embedder", "Media type", "Default"], rows)


def build_embedder_dims() -> str:
    rows = [
        [f"`{e.name}`", f"`{e.media_type_id}`" + (" (default)" if e.is_default else ""), str(e.embedding_dim)]
        for e in _sorted_embedders()
    ]
    return _table(["Embedder", "Media type", "D"], rows)


def build_media_types() -> str:
    """Media types with their default embedder and the alternatives."""
    embedders = _sorted_embedders()
    rows = []
    for t in _media_types():
        of_type = [e for e in embedders if e.media_type_id == t.type_id]
        default = next((e for e in of_type if e.is_default), of_type[0] if len(of_type) == 1 else None)
        alternatives = [e for e in of_type if e is not default]
        rows.append(
            [
                f"`{t.type_id}`",
                f"`{default.name}` ({default.display_name})" if default else "— (convert first)",
                f"`{default.model_id}`" if default and default.model_id else "—",
                ", ".join(f"`{e.name}`" for e in alternatives) or "—",
            ]
        )
    return _table(["Media type", "Default embedder", "Model", "Alternative embedders"], rows)


def build_plugin_families() -> str:
    """Family table plus the counting rule, so prose never states a bare number."""
    inv = _inventory()
    from vtscore.plugins.inventory import FAMILIES  # snapshot after app registration

    app_families = {"settings_importers", "settings_exporters", "settings_sources"}
    library = [f for f in FAMILIES if f not in app_families]
    app = [f for f in FAMILIES if f in app_families]

    # The label lives on the FamilyProvider; reach it through the registry.
    from vtscore.plugins import inventory as _inv_mod

    def label(fam: str) -> str:
        provider = _inv_mod._FAMILIES_REGISTRY.get(fam)
        return provider.label if provider is not None else fam

    rows = [
        [f"`{fam}`", "app" if fam in app_families else "library", label(fam), str(len(inv.get(fam, [])))]
        for fam in FAMILIES
    ]
    counting_rule = (
        f"A **plugin family** is a registry enumerated by `vtscore.plugins.inventory` "
        f"(`python app.py --list-plugins`): {len(library)} library families self-register "
        f"when the library imports, and {len(app)} app-tier families (settings "
        f"importers/exporters/sources) are added by "
        f"`vtsearch.shim.register_app_plugin_families()` at app startup — "
        f"{len(FAMILIES)} in total. Counts below are the built-in plugins shipped "
        f"in-tree; third-party entry-point plugins add to them."
    )
    return counting_rule + "\n\n" + _table(["Family", "Tier", "Registry", "Built-in plugins"], rows)


def build_plugin_family_roster(family: str) -> str:
    """Roster of one plugin family: name, display name, description."""
    inv = _inventory()
    if family not in inv:
        raise KeyError(f"unknown plugin family {family!r}; known: {', '.join(sorted(inv))}")
    entries = sorted(inv[family], key=lambda e: e.name)
    if family == "converters":
        rows = [
            [
                f"`{e.name}`",
                f"`{e.extra.get('source_type', '?')}` → `{e.extra.get('target_type', '?')}`",
                e.display_name,
                e.description,
            ]
            for e in entries
        ]
        return _table(["Converter", "Conversion", "Display name", "Description"], rows)
    rows = [[f"`{e.name}`", e.display_name, e.description] for e in entries]
    return _table(["Name", "Display name", "Description"], rows)


def build_demos(type_id: str) -> str:
    """Demo-dataset table for one media type, sizes included."""
    types = {t.type_id: t for t in _media_types()}
    if type_id not in types:
        raise KeyError(f"unknown media type {type_id!r}; known: {', '.join(sorted(types))}")
    demos = types[type_id].demo_datasets
    rows = []
    for d in demos:
        size = f"~{d.download_size_mb:g} MB" if d.download_size_mb else "—"
        rows.append([f"**{d.id}**", d.description, size])
    return _table(["Demo", "Description", "Download"], rows)


LESSONS_DIR = REPO_ROOT / "scripts" / "experiments" / "lessons"
LESSON_TITLE_RE = re.compile(r"^# (?P<date>\d{4}-\d{2}-\d{2})\s*—\s*(?P<title>.+)$")


def build_lessons_index() -> str:
    """Index of `scripts/experiments/lessons/`, newest first.

    One incident per file is what keeps concurrent experiment branches from
    conflicting: two studies each recording a lesson add two *different* files
    rather than two appends to the same end of one.  This index is the price —
    it is the one shared line, which is why it is generated: if two branches do
    collide here, re-run the generator rather than merging the table by hand.
    """
    rows = []
    # Newest day first; within a day, alphabetical, because the flat file it
    # replaced recorded no finer ordering than the date.
    for path in sorted(
        LESSONS_DIR.glob("*.md"), key=lambda p: (p.name[:10], [-ord(c) for c in p.name[10:]]), reverse=True
    ):
        first = path.read_text(encoding="utf-8").splitlines()[0]
        match = LESSON_TITLE_RE.match(first)
        if not match:
            raise SystemExit(
                f"ERROR: {path.relative_to(REPO_ROOT)} must start with '# YYYY-MM-DD — title'; found {first!r}"
            )
        title = match.group("title")
        issues = sorted(set(re.findall(r"#(\d+)", title)), key=int)
        # The issue numbers are pulled out into their own column, so strip the
        # now-duplicated trailing "(#1234)" the older titles carry.
        stripped = re.sub(r"\s*\(#[\d\s/#]+\)\s*$", "", title).strip()
        rows.append(
            [
                match.group("date"),
                f"[{stripped}](lessons/{path.name})",
                ", ".join(f"#{n}" for n in issues) or "—",
            ]
        )
    return _table(["Date", "Lesson", "Issue"], rows)


def build_region(region_id: str) -> str:
    fixed = {
        "embedders": build_embedders,
        "embedder-files": build_embedder_files,
        "embedder-dims": build_embedder_dims,
        "media-types": build_media_types,
        "plugin-families": build_plugin_families,
        "lessons-index": build_lessons_index,
    }
    if region_id in fixed:
        return fixed[region_id]()
    if region_id.startswith("plugins:"):
        return build_plugin_family_roster(region_id.removeprefix("plugins:"))
    if region_id.startswith("demos:"):
        return build_demos(region_id.removeprefix("demos:"))
    raise KeyError(f"no builder for generated region {region_id!r}")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def tracked_markdown_files() -> list[Path]:
    out = subprocess.run(["git", "ls-files", "*.md"], cwd=REPO_ROOT, capture_output=True, text=True, check=True).stdout
    return [REPO_ROOT / line for line in out.splitlines() if line]


def regenerate_file(path: Path) -> tuple[str, str, list[str]]:
    """Return (old_text, new_text, region_ids) for *path*."""
    old = path.read_text(encoding="utf-8")
    ids: list[str] = []

    def _sub(match: re.Match) -> str:
        region_id = match.group("id")
        ids.append(region_id)
        body = build_region(region_id)
        return f"{match.group(1)}{NOTE}\n\n{body}\n\n{match.group(4)}"

    new = REGION_RE.sub(_sub, old)
    # Any marker the region regex did not consume is a mismatched or unclosed
    # marker pair — fail loudly rather than silently leaving it un-generated.
    leftover = len(ANY_MARKER_RE.findall(new)) - 2 * len(ids)
    if leftover:
        raise SystemExit(
            f"ERROR: {path.relative_to(REPO_ROOT)} has unmatched GENERATED markers "
            f"(a BEGIN without its END, or mismatched region ids)."
        )
    return old, new, ids


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if any generated region is stale")
    args = parser.parse_args()

    seen_regions: set[str] = set()
    stale: list[Path] = []
    for path in tracked_markdown_files():
        text = path.read_text(encoding="utf-8")
        if "<!-- BEGIN GENERATED:" not in text:
            continue
        old, new, ids = regenerate_file(path)
        seen_regions.update(ids)
        if new != old:
            rel = path.relative_to(REPO_ROOT)
            if args.check:
                stale.append(path)
                diff = difflib.unified_diff(
                    old.splitlines(keepends=True), new.splitlines(keepends=True), str(rel), str(rel)
                )
                sys.stdout.writelines(list(diff)[:60])
            else:
                path.write_text(new, encoding="utf-8")
                print(f"regenerated {rel}")

    # Coverage invariant: every media type that declares demo datasets must
    # have its demos:<type_id> region somewhere in the docs.
    missing = [
        f"demos:{t.type_id}" for t in _media_types() if t.demo_datasets and f"demos:{t.type_id}" not in seen_regions
    ]
    if missing:
        print(
            "ERROR: media types with demo datasets but no generated docs region: "
            + ", ".join(missing)
            + " (add the region to docs/demos.md)"
        )
        return 1

    if stale:
        print()
        print("Generated doc inventories are stale in:")
        for path in stale:
            print(f"  {path.relative_to(REPO_ROOT)}")
        print(REGEN_HINT)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
