#!/bin/bash
set -euo pipefail

# Auto-discover plugin requirements.txt files and regenerate
# requirements/plugins.txt, then install everything.
#
# Each plugin (importer, exporter, media type, etc.) declares its own
# dependencies in a local requirements.txt.  This script finds them all,
# writes a requirements/plugins.txt with -r references, and pip-installs it.
#
# A new developer just drops a requirements.txt in their plugin directory —
# the next run of this script (or `pip install -r requirements/base.txt`)
# picks it up automatically.
#
# Usage:
#   bash scripts/install-plugin-deps.sh             # discover + install
#   bash scripts/install-plugin-deps.sh --dry-run   # just regenerate the file

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REQ_DIR="$REPO_ROOT/requirements"
PLUGINS_FILE="$REQ_DIR/plugins.txt"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Collect all plugin requirements.txt files.
REQ_FILES=()
while IFS= read -r -d '' f; do
    REQ_FILES+=("$f")
done < <(find "$REPO_ROOT/vtsearch" -name "requirements*.txt" -print0 | sort -z)

# Write requirements/plugins.txt with -r references. Paths are written
# relative to the plugins.txt file's own directory (i.e. requirements/),
# so pip's per-file resolution finds them whether pip is invoked from the
# repo root or from anywhere else.
{
    echo "# Auto-generated by scripts/install-plugin-deps.sh — do not edit manually."
    echo "# Regenerate with:  bash scripts/install-plugin-deps.sh"
    echo "#"
    echo "# Each line references a plugin's own requirements.txt so that"
    echo "# 'pip install -r requirements/base.txt' cascades through the entire tree."
    echo "# Paths are relative to this file (requirements/), so they begin with \`../\`."
    echo ""
    for f in "${REQ_FILES[@]}"; do
        # Path relative to the requirements/ directory.
        echo "-r ../${f#"$REPO_ROOT/"}"
    done
} > "$PLUGINS_FILE"

echo "Found ${#REQ_FILES[@]} plugin requirements.txt files."
echo "Wrote $PLUGINS_FILE"

if $DRY_RUN; then
    echo "(dry run — no packages installed)"
    exit 0
fi

echo "Installing plugin dependencies..."
pip install -r "$PLUGINS_FILE" -q
echo "Plugin dependencies installed."
